### PR TITLE
[ISSUE #405] Fix custom nacos server logs path in application* profile

### PR DESCRIPTION
**Pull request by anjia0532**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change
1. unified log file charset to utf-8 (**break feature**)
2. support custom logs path(keep old settings to default,e.g. `${user.home}/nacos/logs`, `${user.home}/diamond/logs`,`${nacos.home}/logs`)

## Brief changelog

1. change charset to UTF-8(replace GBK or utf8) (java spec https://docs.oracle.com/javase/8/docs/technotes/guides/intl/encoding.doc.html both of java.io and java.nio support utf-8(because utf-8 alias utf8))

2. support custom nacos server logs path in application* profile(key:nacos.logs.path)

## Verifying this change

```bash
$ cd nacos
$  mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true -T 10
$  mvn -Prelease-nacos clean install -U -T 10
$ cd ./distribution/target/nacos-server-0.6.0/nacos/conf
$ echo "nacos.logs.path=./logs" >> application.properties
$ cd ../bin/
$ startup -m standalone
$ dir logs
// output all of server logs file.
```

Follow this checklist to help us incorporate your contribution quickly and easily:

* [x] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [x] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Comment by anjia0532** [comment]
fixed #405

**Comment by hxy1991** [comment]
Hi, please sign Contributor License Agreement, thanks.

**Comment by anjia0532** [comment]
done

**Comment by hxy1991** [comment]
@anjia0532 Please resolved the conflicts, thanks.

**Comment by anjia0532** [comment]
我提交时，没有冲突，你们将logback.xml中的tab换成了4个空格后，跟我当时提交的产生了冲突[捂脸]
我没有写权限，没法解决冲突啊。
我基于现在的master分支，重新fork&change&push?

**Comment by hxy1991** [comment]
> 我提交时，没有冲突，你们将logback.xml中的tab换成了4个空格后，跟我当时提交的产生了冲突[捂脸]
> 我没有写权限，没法解决冲突啊。
> 我基于现在的master分支，重新fork&change&push?

@anjia0532 你在本地把 nacos develop 分支合到你的 master 分支，提交下就可以了。

image

**Comment by anjia0532** [comment]
哥，这是nacos的开发者执行的。在alibaba/nacos下pull anjia0532/nacos为master，然后`git rm console/src/main/resources/diamond-server-logback.xml` 然后合并，并push到你们的develop里。

如果我在我的repo里执行，是没有差异的。如果clone alibaba/nacos然后修改remote为anjia0532/nacos，最后一大坨冲突。

**Pull request merged**
