### PR TITLE
[ISSUE #7941] FIX: Missing parameters 'dataId' and 'group'.

### PR DESCRIPTION
**Pull request by myifeng**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

FIX: Missing parameters 'dataId' and 'group'.

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [x] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [x] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Review by KomachiSion — DISMISSED** [review]

**Comment by KomachiSion** [comment]
Did you test the console feature of history after changes?

**Comment by myifeng** [comment]
> Did you test the console feature of history after changes?

This modification only completes the two missing parameters, so the returned response code is not 500 but 200. 
The test returns a status code of 200, as expected.

**Comment by myifeng** [comment]
> > Did you test the console feature of history after changes?
> 
> This modification only completes the two missing parameters, so the returned response code is not 500 but 200. The test returns a status code of 200, as expected.

Sorry, there still missing a parameter, I'll fix it.

```
/**
     * Query previous config history information. notes:
     *
     * @param id     config_info id
     * @param dataId dataId  @since 2.0.3
     * @param group  groupId  @since 2.0.3
     * @param tenant tenantId  @since 2.0.3
     * @return history config info
     * @since 2.0.3 add {@link Secured}, dataId, groupId and tenant for history config permission check.
     * @since 1.4.0
     */
    @GetMapping(value = "/previous")
    @Secured(action = ActionTypes.READ, signType = SignType.CONFIG)
    public ConfigHistoryInfo getPreviousConfigHistoryInfo(@RequestParam("dataId") String dataId,
            @RequestParam("group") String group,
            @RequestParam(value = "tenant", required = false, defaultValue = StringUtils.EMPTY) String tenant,
            @RequestParam("id") Long id) throws AccessException {
    }
```

**Comment by myifeng** [comment]
The tenant parameter does not need to be passed in this request because lib.js already handles it.
https://github.com/alibaba/nacos/blob/fabf6d43a56f1b266f59dfb908dd69f72d26774d/console-ui/src/lib.js#L46

**Review by KomachiSion — APPROVED** [review]

**Pull request merged**
