### PR TITLE
[ISSUE #9135] Remove redundant nullcheck code.

### PR DESCRIPTION
**Pull request by jjastan**
Resolve problem https://github.com/alibaba/nacos/issues/9135 redundant nullcheck code.

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Comment by chenhao26-nineteen** [comment]
Please sign CLA first

**Comment by jjastan** [comment]
CLA signed.

**Review by chenhao26-nineteen — DISMISSED** [review]

**Comment by chenhao26-nineteen** [comment]
IT not pass

**Comment by jjastan** [comment]
> IT not pass

这条测试用例在本地是可以跑过的, 改的代码也不涉及它。
请问下现在我需要做什么操作才能继续把这个PR往下走。
谢谢！
image
image

**Comment by chenhao26-nineteen** [comment]
Can you make some minor changes  and run IT again？

**Comment by jjastan** [comment]
> Can you make some minor changes and run IT again？

This commit solve the different branches return the same result in method CapacityService#initGroupCapacity.

**Review by KomachiSion — APPROVED** [review]

**Pull request merged**
