### PR TITLE
[#3388]Remove the deleted roles and permissions info during reloading role info

### PR DESCRIPTION
**Pull request by yanjunnf**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

#3388 

## Brief changelog

We should remove these already deleted roles, permissions during reloading nacos role info.

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Comment by yanjunnf** [comment]
Just checked job log, all projects built successfully， but found an error in test project:
Tests run: 33, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 222.204 sec <<< FAILURE! - in com.alibaba.nacos.test.config.ConfigAPI_CITCase
nacos_addListener_1(com.alibaba.nacos.test.config.ConfigAPI_CITCase)  Time elapsed: 25.028 sec  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 25000 milliseconds
	at com.alibaba.nacos.test.config.ConfigAPI_CITCase.nacos_addListener_1(ConfigAPI_CITCase.java:372)

But this test case successed on the other 2 jobs, so can I rebuild it ?

**Comment by yanjunnf** [comment]
Just checked job log, all projects built successfully， but found an error in test project:
Tests run: 33, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 222.204 sec <<< FAILURE! - in com.alibaba.nacos.test.config.ConfigAPI_CITCase
nacos_addListener_1(com.alibaba.nacos.test.config.ConfigAPI_CITCase)  Time elapsed: 25.028 sec  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 25000 milliseconds
	at com.alibaba.nacos.test.config.ConfigAPI_CITCase.nacos_addListener_1(ConfigAPI_CITCase.java:372)

But this test case successed on the other 2 jobs, so can I rebuild it ?

**Comment by KomachiSion** [comment]
Can you talk about why you close this PR?

**Comment by yanjunnf** [comment]
Why do not clear roleSet, roleInfoMap and permissionInfoMap before putAll/addAll?
The clear method cannot provide the whole logic as a atomic operation.
For example, roleSet.clear() finished to execute, but this thread is suspended, then antoher thread try to get all roles, it get empty list since the roleSet object was cleared.

**Comment by yanjunnf** [comment]
Can you talk about why you close this PR?
The PR build failed, I don't know how to restart build(Looks like the build failure is nothing to do with my commits.), So i will close it and recreate one.

**Pull request closed without merging**
