### PR TITLE
[ISSUE#5234] solve the problem that page can be edited while publishing-config request is processing  

### LINKED ISSUE #5234: The page can be edited while the publishing-config request is processing
**Is your feature request related to a problem? Please describe.**
when i publish the config, and the backend is blocked, the config-editing page still can be edited

**Describe the solution you'd like**
after a publishing-config request, the page should pending until request finished or time out

**Describe alternatives you've considered**

**Additional context**

https://user-images.githubusercontent.com/43567778/112855173-2784fb80-90e1-11eb-8806-8a1ec4db65aa.mp4

### PR DESCRIPTION
**Pull request by ShawnSiao**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

fix #5234

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Comment by ShawnSiao** [comment]
https://user-images.githubusercontent.com/21096533/113319132-b729e480-9343-11eb-94b6-ecb7f39dd564.mp4

**Comment by KomachiSion** [comment]
There are some conflict with main.js.  please solve it first

**Review by KomachiSion — CHANGES_REQUESTED** [review]
conflict.

**Comment by ShawnSiao** [comment]
@KomachiSion the conflict has been resloved

**Review by KomachiSion — APPROVED** [review]

**Pull request merged**
