### PR TITLE
[ISSUE-#4179] Add index for db.user and db.password

### PR DESCRIPTION
**Pull request by horizonzy**
## What is the purpose of the change
For-#4179, add index for db.user and db.password, to avoid some situation that it contains symbol `,`.

### CODE REVIEW

**Review by KomachiSion — APPROVED** [review]

**Comment by chuntaojun** [comment]
if db.user and db.password not index info, it mean is global user info, so I think you need to describe the two cases separately

**Comment by KomachiSion** [comment]
Should we describe this issue in document?

If add all item in default application.properties, it looks too confused.

**Comment by chuntaojun** [comment]
> Should we describe this issue in document?
> 
> If add all item in default application.properties, it looks too confused.

agree，wo need to describe this issue in document

**Comment by horizonzy** [comment]
Agreen, I will add some description to doc later.

**Comment by horizonzy** [comment]
Default config with index will be better I think.

**Review by KomachiSion — APPROVED** [review]

**Pull request merged**
