### PR TITLE
Develop issue#{7393}

### PR DESCRIPTION
**Pull request by SteafanMrZhou**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

For issue#{7393}
#7393

### CODE REVIEW

**Comment by SteafanMrZhou** [comment]
@realJackSun

**Review by KomachiSion — CHANGES_REQUESTED** [review]
your pr description is instanceController, but the code include many other Controller. I think you should focus on one Controller in one PR.

**Comment by KomachiSion** [comment]
I found PR has no changes.

**Comment by KomachiSion** [comment]
two problem:
1. confilcts with classes
2. auth is an plugin, but your add the `token` in console module, I think it is not a good design.

**Comment by SteafanMrZhou** [comment]
Accroding to the latest version,the issue was modified,just close it.

**Comment by KomachiSion** [comment]
Relative and move to #8308

**Pull request closed without merging**
