### PR TITLE
[ISSUE #8358] make this anonymous inner class a lambda

### PR DESCRIPTION
**Pull request by david6969xin**
the purpose of the change：simplify some code

### CODE REVIEW

**Comment by cuuwolf** [comment]
Enviado desde mi iPhone

El 12 may 2022, a la(s) 7:14, CLAassistant ***@***.***> escribió:

﻿
 
Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our Contributor License Agreement before we can accept your contribution.
You have signed the CLA already but the status is still pending? Let us recheck it.

**Comment by david6969xin** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月13日(星期五) 上午8:41
***@***.***&gt;;
抄送:&nbsp;"Just for ***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] [ISSUE #8358] make this anonymous inner class a lambda (PR #8359)





 
 
 Enviado desde mi iPhone
 
 El 12 may 2022, a la(s) 7:14, CLAassistant ***@***.***&gt; escribió:
 
 ﻿
  
 Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our Contributor License Agreement before we can accept your contribution.
 You have signed the CLA already but the status is still pending? Let us recheck it.

**Review by KomachiSion — CHANGES_REQUESTED** [review]
The PR contain much package and changes, can you split this PR to multiples?

**Comment by david6969xin** [comment]
@KomachiSion ok，i will split this PR according to the module name

**Comment by KomachiSion** [comment]
> @KomachiSion ok，i will split this PR according to the module name

OK, I will close this PR, and review new PRs.

**Pull request closed without merging**
