### PR TITLE
[ISSUE #3907] when publishConfig, if type is absent, set default value 'text'

### PR DESCRIPTION
**Pull request by horizonzy**
## What is the purpose of the change
fix-#3907

### CODE REVIEW

**Comment by KomachiSion** [comment]
I think it can't fix the issue, it will cause the type be replaces with text.

**Comment by horizonzy** [comment]
> I think it can't fix the issue, it will cause the type be replaces with text.

It just replaced when type not setted. when type not setted, we set default value as 'text' or throw exception?

**Comment by KomachiSion** [comment]
I think the solution should be to modifying config-client, get the type by dataId suffix, if not suffix or unsupported suffix, use text as default.

**Comment by horizonzy** [comment]
@KomachiSion @chuntaojun 
#2662 is no response, use this pr to fix it.

**Review by KomachiSion — APPROVED** [review]

**Pull request merged**
