### PR TITLE
Add PostgreSQL supports

### PR DESCRIPTION
**Pull request by richwxd**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

Add PostgreSQL supports

## Brief changelog

1. upgrade spring-boot dependency
2. add postgresql supports in external storage

## Verifying this change

1. change application.properties, db chuck
2. create postgresql db and create tables
3. run nacos

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Comment by KomachiSion** [comment]
I don't think this implementation is great. it will be hard to maintainer.

**Comment by richwxd** [comment]
So please point out the weakness, then we can fix them. The reason for this submission is that hoping other developers to improve since this is a "Apache-2.0 License" community project.

**Comment by KomachiSion** [comment]
The current implementation is hard to maintain and expand. And does not meet the closure principle.

We are planing to abstract the SQL generator for Nacos in future version. After that the PG and other DB can add with plugin.

**Comment by KomachiSion** [comment]
Of course you can fork and modified like this PR, and use it.
But nacos community will not merge it.

**Pull request closed without merging**
