### PR TITLE
Issues 11241  remove ControllerMethodsCache

### PR DESCRIPTION
**Pull request by huangkemingyyds**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change
https://github.com/alibaba/nacos/issues/11241

## Brief changelog

1. 删除了ControllerMethodsCache相关的代码，使用了现成的RequestMappingHandlerMapping方法来处理。
2. application.properties，新增默认配置：spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Review by KomachiSion — CHANGES_REQUESTED** [review]
1. 建议不要去除，而是加一个开关来替换，默认可以使用spring的mapping。
2. 设置为ANY_Matcher 会不会有安全漏洞的风险。

**Comment by huangkemingyyds** [comment]
分析:

1.移除的优势就是去除启动扫描，如果再加个配置开关，还是要存在启动扫描。
2.如果单纯使用mapping来做，确实可能会来带安全组的问题，并且又不利于未来的在url方面的管控拓展。

我认为这是个多余的工作，可以关闭此话题。

**Comment by huangkemingyyds** [comment]
> 分析:
> 
> 1.移除的优势就是去除启动扫描，如果再加个配置开关，还是要存在启动扫描。
> 2.如果单纯使用mapping来做，确实可能会来带安全组的问题，并且又不利于未来的在url方面的管控拓展。
> 
> 我认为这是个多余的工作，可以关闭此话题。

@KomachiSion

**Comment by huangkemingyyds** [comment]
> 1. 建议不要去除，而是加一个开关来替换，默认可以使用spring的mapping。
> 2. 设置为ANY_Matcher 会不会有安全漏洞的风险。

暂时关闭， 我可以改成第一点在提交看看。  第二点无法评估。

**Pull request closed without merging**
