### PR TITLE
feat: add RPC timer metrics

### PR DESCRIPTION
**Pull request by luckyxiaoqiang**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

[add RPC timer metrics](https://github.com/alibaba/nacos/issues/10846)

Example:
```
# HELP nacos_rpc_server_requests_seconds  
# TYPE nacos_rpc_server_requests_seconds summary
nacos_rpc_server_requests_seconds{code="0",exception="None",outcome="SUCCESS",protocol="grpc",type="ConfigQueryRequest",quantile="0.5",} 0.001998848
nacos_rpc_server_requests_seconds{code="0",exception="None",outcome="SUCCESS",protocol="grpc",type="ConfigQueryRequest",quantile="0.9",} 0.001998848
nacos_rpc_server_requests_seconds{code="0",exception="None",outcome="SUCCESS",protocol="grpc",type="ConfigQueryRequest",quantile="0.95",} 0.004030464
nacos_rpc_server_requests_seconds{code="0",exception="None",outcome="SUCCESS",protocol="grpc",type="ConfigQueryRequest",quantile="0.99",} 0.005996544
nacos_rpc_server_requests_seconds_count{code="0",exception="None",outcome="SUCCESS",protocol="grpc",type="ConfigQueryRequest",} 34.0
nacos_rpc_server_requests_seconds_sum{code="0",exception="None",outcome="SUCCESS",protocol="grpc",type="ConfigQueryRequest",} 0.062
nacos_rpc_server_requests_seconds{code="0",exception="None",outcome="SUCCESS",protocol="grpc",type="InstanceRequest",quantile="0.5",} 9.8304E-4
nacos_rpc_server_requests_seconds{code="0",exception="None",outcome="SUCCESS",protocol="grpc",type="InstanceRequest",quantile="0.9",} 9.8304E-4
nacos_rpc_server_requests_seconds{code="0",exception="None",outcome="SUCCESS",protocol="grpc",type="InstanceRequest",quantile="0.95",} 9.8304E-4
nacos_rpc_server_requests_seconds{code="0",exception="None",outcome="SUCCESS",protocol="grpc",type="InstanceRequest",quantile="0.99",} 9.8304E-4
nacos_rpc_server_requests_seconds_count{code="0",exception="None",outcome="SUCCESS",protocol="grpc",type="InstanceRequest",} 1.0
nacos_rpc_server_requests_seconds_sum{code="0",exception="None",outcome="SUCCESS",protocol="grpc",type="InstanceRequest",} 0.001
```

## Brief changelog
add RPC timer metrics

### CODE REVIEW

**Review by KomachiSion — CHANGES_REQUESTED** [review]
Recommend add full information.

Like exception class, return code, request type.

you can research the tomcat metrics.

**Comment by luckyxiaoqiang** [comment]
> Recommend add full information.
> 
> Like exception class, return code, request type.
> 
> you can research the tomcat metrics.

Error code, request type are already added. Exception mostly is `NacosException`, is it really needed?

**Comment by KomachiSion** [comment]
> > Recommend add full information.
> > Like exception class, return code, request type.
> > you can research the tomcat metrics.
> 
> I added metrics example in the PR description, please take a look again. Error code, request type are already added. Exception mostly is `NacosException`, is it really needed?

For normal handler, the exception in handler maybe not `NacosException`, So the exception type also can help to find the problem. I still recommend you research the tomcat metrics. It include `uri`,`method`(grpc request type) ,exception, code, and so on.

I think your implementation has include most of information, but add exception and success tag will be better.

**Comment by KomachiSion** [comment]
BTW, the the `nacos_rpc` should change to `nacos_grpc`? or still use `nacos_rpc` but add `protocol=grpc` label?

**Comment by luckyxiaoqiang** [comment]
@KomachiSion Please continue to review.

**Review by KomachiSion — CHANGES_REQUESTED** [review]
I think you has mistake for the exception class.

you should handle the throwable in Acceptor, not inject into response.

**Comment by luckyxiaoqiang** [comment]
> I think you has mistake for the exception class.
> 
> you should handle the throwable in Acceptor, not inject into response.

This is the old logic, I just done small refactor.

**Comment by KomachiSion** [comment]
Refactor means don't change the old action, requests, responses , your changes add some field in response, which will cause the communication changed, Though it might compatible with old version, but it changed.

And For issue and PR, it's a new feature.  The new feature implementation is not right I think, So I comment and want you change it.

More simple implementation is catch the Exception from handle and set to metrics. If handle no exception, no need add the exception to metrics, just set the result code and set `None` in metrics is ok. I have no idea why you change the response to do.

**Comment by KomachiSion** [comment]
No more response from author, and PR not changes with conflicts. Close first.

**Pull request closed without merging**
