### PR TITLE
Feature #8941 Support Fuzzy Query in Authority Control.

### PR DESCRIPTION
**Pull request by zhouchunhai**
## What is the purpose of the change

Feature #8941 Support Fuzzy Query in Authority Control.

## Brief changelog

support fuzzy query for user, role, permission management

### CODE REVIEW

**Comment by KomachiSion** [comment]
Can you split this PR to at least two PR?

**Comment by zhouchunhai** [comment]
ok, i will submit another PR to fix underscore problem

**Comment by zhouchunhai** [comment]
I revert the second commit, which is meant to fix the underscore problem.But the two commits are associated, so only the first was merged, I can submit another.

**Comment by KomachiSion** [comment]
I see this PR still contain the ui and server plugin, I want you split this PR at lease two PR(one is server plugin api change, and other is ui. If you can split server plugin change to more PR will be better).

**Pull request closed without merging**
