### PR TITLE
when publishconfig, get the type through the dataid suffix, if there is no suffix or unsupported suffix, use the text as the default value

### LINKED ISSUE #3907: 调用 publishConfig 会覆盖数据库 type 字段
版本：Spring Boot 2.3.3，Nacos Client 1.3.0，Nacos Server 1.3.2

代码 NacosConfigService 类 publishConfigInner 第 252 行 result = agent.httpPost(url, headers, params, encode, POST_TIMEOUT);

params 参数如下：

image

缺少 type 参数，请求后会覆盖数据库原本的 type，导致 type 为 null。

Nacos 控制台：

image

以下是官方接口参数：

image

直接调用接口，忽略 type 参数和上面的结果相同。

image

### PR DESCRIPTION
**Pull request by ChasingInTheWind**
Fix #3907

## What is the purpose of the change

XXXXX

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Comment by horizonzy** [comment]
I think this logic which handle suffix is the client logic. In server, if you want to judge the text is valid, just check the type is 'Text' or other type which announce in server.

**Comment by KomachiSion** [comment]
> I think this logic which handle suffix is the client logic. In server, if you want to judge the text is valid, just check the type is 'Text' or other type which announce in server.

If we use old client but new server, it will also is null or always text? I think client need contain parse type logic and send type to server, and server also need this logic if no type receivce.

BTW, the parsing logic can be extract to a util to common, client and server both use it.

What do you think?

**Comment by horizonzy** [comment]
> > I think this logic which handle suffix is the client logic. In server, if you want to judge the text is valid, just check the type is 'Text' or other type which announce in server.
> 
> If we use old client but new server, it will also is null or always text? I think client need contain parse type logic and send type to server, and server also need this logic if no type receivce.
> 
> BTW, the parsing logic can be extract to a util to common, client and server both use it.
> 
> What do you think?

I prefer think suffix is business, it should be realized by third integrate framework, such as spring-nacos-context, nacos just save the type which is send from client. In server, we just check the type is valid (blank or is not announced in server). if invalid, set a default value 'text' to the type.

**Comment by horizonzy** [comment]
Now in nacosConfigService, we cat't set type when publishConfig, maybe we can supply a way let user set type when publicConfig. I am not prefer parse type by suffix, If we do, almost dataId will contains suffiix, even the content isn't match suffix. And some user still don't set data with suffix, in server, we still to handle that case.

**Comment by ChasingInTheWind** [comment]
> > I think this logic which handle suffix is the client logic. In server, if you want to judge the text is valid, just check the type is 'Text' or other type which announce in server.
> 
> If we use old client but new server, it will also is null or always text? I think client need contain parse type logic and send type to server, and server also need this logic if no type receivce.
> 
> BTW, the parsing logic can be extract to a util to common, client and server both use it.
> 
> What do you think?

I agree with horizonzy view that the service should only verify the validity of the data and the default value

**Comment by KomachiSion** [comment]
If server only verify type, this PR should be close, because this implementation is parsing suffix and set it as type.

**Comment by KomachiSion** [comment]
Refer to #3915

**Comment by ChasingInTheWind** [comment]
> Refer to #3915

ok

**Pull request closed without merging**
