### PR TITLE
[ISSUE #8275] Fix ClassCastException: io.grpc.ClientInterceptors$InterceptorChannel cannot be cast to io.grpc.ManagedChannel

### PR DESCRIPTION
**Pull request by ZhengBing520**
## What is the purpose of the change

https://github.com/alibaba/nacos/issues/8275

## Brief changelog

Get the created channel directly

## Verifying this change

no output error log

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Comment by KomachiSion** [comment]
It seems still miss unit test?

**Comment by ZhengBing520** [comment]
> It seems still miss unit test?

I haven't found the unit test of grpc yet. I need to think about it
After modifying the code, start the cluster and find that it is in normal use

**Comment by ZhengBing520** [comment]
> > It seems still miss unit test?
> 
> I haven't found the unit test of grpc yet. I need to think about it After modifying the code, start the cluster and find that it is in normal use

Whether to refer to the following unit tests
core: test com.alibaba.nacos.core.remote.grpc
image

**Comment by ZhengBing520** [comment]
> > It seems still miss unit test?
> 
> I haven't found the unit test of grpc yet. I need to think about it After modifying the code, start the cluster and find that it is in normal use

Whether to refer to the following unit tests
core: test com.alibaba.nacos.core.remote.grpc
image

**Comment by KomachiSion** [comment]
You can add an unit test class and write some unit test for your changes.

**Comment by ZhengBing520** [comment]
> You can add an unit test class and write some unit test for your changes.

hello @KomachiSion ，Unit test has been added, please check it

**Comment by KomachiSion** [comment]
> > You can add an unit test class and write some unit test for your changes.
> 
> hello @KomachiSion ，Unit test has been added, please check it

Great, I will merge it if CI pass.

**Comment by ZhengBing520** [comment]
> > > You can add an unit test class and write some unit test for your changes.
> > 
> > 
> > hello @KomachiSion ，Unit test has been added, please check it
> 
> Great, I will merge it if CI pass.

I saw this anomaly yesterday, and there is still a local one that has not been submitted, so I will submit it now；

**Comment by ZhengBing520** [comment]
> > > You can add an unit test class and write some unit test for your changes.
> > 
> > 
> > hello @KomachiSion ，Unit test has been added, please check it
> 
> Great, I will merge it if CI pass.

CI passed,

**Review by KomachiSion — APPROVED** [review]

**Pull request merged**
