### PR TITLE
[ISSUE #8107] 403 go to home page when modify user's password 

### LINKED ISSUE #8107: nacos2.0.4 开启鉴权后 所有账号更改密码报错
image

### PR DESCRIPTION
**Pull request by onewe**
- use IdentityContextHolder instead of get user information from session

Problem:
问题:
Users restart nacos server and do not login again then users update password will get an error `authorization failed`
用户重启了 nacos server 端,并未重新登录. 在做修改用户密码时提示`authorization failed`

Cause:
原因:
The session information was lost by restart.
重启客户端session信息丢失

Fix:
修复:
Use `IdentityContextHolder` instead of sessions, When requests are cross the `AuthFilter`, the `AuthFilter` will set a `IdentityContext` object into `IdentityContextHolder` and clean it in the end
使用 `IdentityContextHolder` 替代从 session 中获取用户信息. 每次请求经过 `AuthFilter`  把 `IdentityContext` 对象放入到 `IdentityContextHolder` 中并在请求结束时清空 `IdentityContextHolder`

Close #8107

Please do not create a Pull Request without creating an issue first.

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [x] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Review by KomachiSion — CHANGES_REQUESTED** [review]
1. 慎用ThreadLocal
2. 有必要修复吗？ 我理解刷新一下页面即可。服务端重启之后，链接闪断，session关闭，我觉得是正常的

**Comment by onewe** [comment]
主要界面不会让用户退出重新登录,刷新页面问题同样存在

**Comment by onewe** [comment]
或者 我改改前端 401 之后就直接跳转到主页面,让用户重新登录即可

**Comment by KomachiSion** [comment]
> 或者 我改改前端 401 之后就直接跳转到主页面,让用户重新登录即可

这个方法或许比较好

**Comment by onewe** [comment]
@KomachiSion 搞定

**Review by KomachiSion — APPROVED** [review]

**Comment by KeithTt** [comment]
遇到了这个问题，很奇怪的是，用默认管理员用户 nacos 修改普通用户密码也会自动登出跳转到登陆页面。

一般情况下，不是用户修改自身密码才会登出重新登陆吗？

**Comment by onewe** [comment]
@KeithTt 这个问题的本质是 `seesion` 失效了 `JWT` 的 `token` 没有失效

**Pull request merged**
