### PR TITLE
[ISSUE #8924]optimize subscriber get generic event type

### LINKED ISSUE #8924: Optimizing abstract class Subscriber suggestion
I found that many Subscriber implementation classes obtain subscribeType as generic classes during reading the source code. The abstract class Subscriber can optimize the subscribeType() method to obtain the generic class of subclasses by default, reducing unnecessary code in the project.
example:
image
image

### PR DESCRIPTION
**Pull request by karsonto**
Close #8924

### CODE REVIEW

**Review by KomachiSion — CHANGES_REQUESTED** [review]
I don't think it's a good way. I will contain many hide informations. I think the old way can make readers fast understand the subscriber sub which events.

**Comment by KomachiSion** [comment]
Please has some discuss in issue first before you submit PR.

**Comment by vergilyn** [comment]
It is not recommended to obtain the `subscribeType` by reflection **every time**.

can reference：<https://github.com/baomidou/mybatis-plus/blob/master/mybatis-plus-extension/src/main/java/com/baomidou/mybatisplus/extension/service/impl/ServiceImpl.java>
image

**Comment by karsonto** [comment]
@vergilyn I know, but the Subscriber will register to publisher once when initialization in constructor,so it is unnecessary to waste memory  to save event class.
image
image

**Pull request closed without merging**
