### PR TITLE
display the namespace on add,edit,detail configuration page #(9827)

### PR DESCRIPTION
**Pull request by githubcheng2978**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

XXXXX

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Comment by githubcheng2978** [comment]
#9827

**Comment by githubcheng2978** [comment]
resolve CLA problem

**Comment by KomachiSion** [comment]
1. The CLA problem has no solved, the commit include two persons. suggest you reset the head and resubmit them and force push to your branch.
2. CI can't pass, please fix them.

**Comment by githubcheng2978** [comment]
Ok , i did this

**Comment by githubcheng2978** [comment]
handling unit test issues

**Comment by KomachiSion** [comment]
The UT problem has been fixed by #9884, you can rebase the develop branch.

**Comment by KomachiSion** [comment]
> [CLA assistant check](https://cla-assistant.io/alibaba/nacos?pullRequest=9845) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=9845) before we can accept your contribution.**1** out of **2** committers have signed the CLA.✅ githubcheng2978❌ ychen
> 
> **ychen** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=9845) it.

The PR contain `ychen` 's commit, Please remove others commits or let it sign CLA.

**Review by shiyiyue1102 — APPROVED** [review]

**Pull request merged**
