### PR TITLE
[ISSUE-#4393] Use PeerId.getEndpoint() to replace new Object

### PR DESCRIPTION
**Pull request by horizonzy**
## What is the purpose of the change
For-#4393

### CODE REVIEW

**Review by KomachiSion — CHANGES_REQUESTED** [review]
The pr id is 4394, but your description and title also link 4394?

**Comment by KomachiSion** [comment]
If this change is so small that hard to create issue, you can only description your change in PR comment.

**Review by zongtanghu — APPROVED** [review]

**Comment by zongtanghu** [comment]
Looks good to me!

**Comment by horizonzy** [comment]
> If this change is so small that hard to create issue, you can only description your change in PR comment.

ok

**Review by chuntaojun — APPROVED** [review]

**Review by KomachiSion — APPROVED** [review]

**Pull request merged**
