### PR TITLE
[Enhancement] Add prometheus api exception handling

### PR DESCRIPTION
**Pull request by karsonto**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

XXXXX

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Review by KomachiSion — CHANGES_REQUESTED** [review]
这么修改的原因是什么？ 如果不给出失败原因会不会误解成获取不到数据？

**Comment by karsonto** [comment]
> 这么修改的原因是什么？ 如果不给出失败原因会不会误解成获取不到数据？

是的，如果控制器抛出nacosException 会导致普罗米修斯解析出错，所以兜底返回空数组就可以了

**Comment by KomachiSion** [comment]
prometheus sd没定义失败的时候应该如何返回吗？

**Comment by karsonto** [comment]
> prometheus sd没定义失败的时候应该如何返回吗？

官方文档没有描述失败时候如何处理请求的返回，只描述了当请求失败时默认会缓存上次成功请求的数据

**Comment by KomachiSion** [comment]
> > prometheus sd没定义失败的时候应该如何返回吗？
> 
> 官方文档没有描述失败时候如何处理请求的返回，只描述了当请求失败时默认会缓存上次成功请求的数据

那是不是应该还是给他们报错比较合理， 返回空数据和失败应该是两个意思

**Comment by karsonto** [comment]
> > > prometheus sd没定义失败的时候应该如何返回吗？
> > 
> > 
> > 官方文档没有描述失败时候如何处理请求的返回，只描述了当请求失败时默认会缓存上次成功请求的数据
> 
> 那是不是应该还是给他们报错比较合理， 返回空数据和失败应该是两个意思

也是，那就包装一下错误信息返回报错吧

**Comment by KomachiSion** [comment]
The IT seems some problem.

**Review by KomachiSion — APPROVED** [review]

**Pull request merged**
