### PR TITLE
[ISSUE #9001] Add snowflake instanceId generation implementation

### PR DESCRIPTION
**Pull request by chenws1012**
Please do not create a Pull Request without creating an issue first.

## Brief changelog

Add snowflake instanceId generation implementation

## Verifying this change

Follow this checklist to help us incorporate your contribution quickly and easily:

* [x] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [x] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Review by KomachiSion — APPROVED** [review]

**Review by KomachiSion — CHANGES_REQUESTED** [review]
How about the grpc request?

**Comment by chenws1012** [comment]
> How about the grpc request?

I don't understand, can you explain it in more detail?

**Comment by KomachiSion** [comment]
> 
> How about the grpc request?
> 
> I don't understand, can you explain it in more detail?

your implementation for now only handle and generate snowflake id when user use http api register, but when users use 2.x client register instance by grpc protocol, the snowflake will not work.

**Comment by chenws1012** [comment]
got it.

**Review by KomachiSion — CHANGES_REQUESTED** [review]
Please add unnit test for your changes, Thanks

**Review by KomachiSion — CHANGES_REQUESTED** [review]
Sorry, I mean, the other classes, which you changes also need add UT for your changes.

Such as `InstanceRequestHandlerTest` , the old UT maybe not assert the instanceId, you should add the assert and should has two cases(one is use default generator and one is snowflake).

**Review by KomachiSion — APPROVED** [review]

**Comment by KomachiSion** [comment]
Sorry, there are some file has no copyright in PR, you can do `mvn -B clean package -Prelease-nacos -Dmaven.test.skip=true` to find out problem in local.

**Comment by KomachiSion** [comment]
I tried serval time to do CI. But still error in mvn build. And has no detail error info.

**Comment by KomachiSion** [comment]
I think It should be github's problem, I will retry after, and you can do `mvn -Prelease-nacos -Dmaven.test.skip=true clean install -U` in your local to try to find out whether has build problem.

**Comment by KomachiSion** [comment]
Still Error, I think you should run 
`mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true`
`mvn -Prelease-nacos -Dmaven.test.skip=true clean install -U` 
`mvn -Prelease-nacos clean test -DtrimStackTrace=false`
in your local, and make sure them can pass before you commit.

**Comment by KomachiSion** [comment]
the UT can't pass. please fix them.

**Comment by KomachiSion** [comment]
Sorry , Can you use `mvn -Prelease-nacos clean test -DtrimStackTrace=false` in you local and make sure it pass first?

**Comment by godhth** [comment]
@i will solve it@

**Pull request closed without merging**
