### PR TITLE
Schedule naming optimization of cp architecture

### PR DESCRIPTION
**Pull request by pengzhengfa**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

XXXXX

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Comment by pengzhengfa** [comment]
@KomachiSion Hello, I have optimized the naming in the schedule of heartbeat and election logic. Please your check it

**Comment by KomachiSion** [comment]
I have merged some class in last PR #3104 . Why you PR again for same class and line?

**Comment by pengzhengfa** [comment]
OK, let me see first

**Comment by KomachiSion** [comment]
And I suggest that you open an issue first for your enhancement. It seems that you want to optimize this part for a long time.

**Comment by pengzhengfa** [comment]
@KomachiSion Hello, I just want to optimize the main logic for the last time, because I have a fatal problem in naming in development

**Comment by KomachiSion** [comment]
> except `GlobalExecutor.java` , other 7 filed has merged by #3104 . Please use rebase to sync your branch and re commit again.

We use squash and merged to merge PR , so the commit log will be squash as one commit.
If you do not rebase or re-checkout branch from latest branch, these commit will be repeated.

**Comment by pengzhengfa** [comment]
@KomachiSion Hello, it has been solved. At present, the main line logical naming optimization has been completed

**Pull request merged**
