### PR TITLE
[ISSUE #2800] .update beatinfo when received instance modify info

### PR DESCRIPTION
**Pull request by horizonzy**
What is the purpose of the change

FIX-#2800

### CODE REVIEW

**Comment by horizonzy** [comment]
@chuntaojun pls check it

**Comment by chuntaojun** [comment]
Please add some single tests

**Comment by horizonzy** [comment]
> single

👌

**Comment by yanlinly** [comment]
please resolve conflict

**Comment by horizonzy** [comment]
pls see the pr #3037. this pr's code is old,I pull a new request.

**Pull request closed without merging**
