### PR TITLE
For #7973, Fix catch excessive exception

### PR DESCRIPTION
**Pull request by xuzhiguang**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

fix bug #7973

## Brief changelog

Fix catch excessive exception

## Verifying this change

checked all

### CODE REVIEW

**Comment by li-xiao-shuang** [comment]
> [CLA assistant check](https://cla-assistant.io/alibaba/nacos?pullRequest=7974) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=7974) before we can accept your contribution.
> 
> **wecantstop** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=7974) it.

sign CLA

**Comment by xuzhiguang** [comment]
> > [CLA assistant check](https://cla-assistant.io/alibaba/nacos?pullRequest=7974) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=7974) before we can accept your contribution.
> > **wecantstop** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> > You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=7974) it.
> 
> sign CLA

不好意思，这个用户名没有加邮箱，我是不是只能重新提PR了

**Comment by li-xiao-shuang** [comment]
> > > [CLA assistant check](https://cla-assistant.io/alibaba/nacos?pullRequest=7974) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=7974) before we can accept your contribution.
> > > **wecantstop** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> > > You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=7974) it.
> > 
> > 
> > sign CLA
> 
> 不好意思，这个用户名没有加邮箱，我是不是只能重新提PR了

你可以选择一个常用的账户，也可以直接把邮箱添加到这个账户里 ，setting/emails

**Comment by xuzhiguang** [comment]
> > > > [CLA assistant check](https://cla-assistant.io/alibaba/nacos?pullRequest=7974) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=7974) before we can accept your contribution.
> > > > **wecantstop** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> > > > You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=7974) it.
> > > 
> > > 
> > > sign CLA
> > 
> > 
> > 不好意思，这个用户名没有加邮箱，我是不是只能重新提PR了
> 
> 你可以选择一个常用的账户，也可以直接把邮箱添加到这个账户里 ，setting/emails

是我提交时设置的用户名（wecantstop）是个无效的用户名，且没有加邮箱，（xuzhiguang）这个账户是正常的。我还有什么操作空间吗

**Pull request closed without merging**
