### PR TITLE
[ISSUE #1654] Fix content hightlight does not work in config detail page

### PR DESCRIPTION
**Pull request by ljhrot**
#1654

## What is the purpose of the change

Fix content hightlight does not work in config detail page

## Brief changelog

Use codemirror to replace inputbox

## Verifying this change

View detail page for config

Follow this checklist to help us incorporate your contribution quickly and easily:

* [x] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Comment by KomachiSion** [comment]
@ljhrot Please solve conflict for main.js

**Comment by ljhrot** [comment]
@KomachiSion Please help me! Is this error?  Why did the previous CI build pass?

```
Tests run: 33, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 221.925 sec <<< FAILURE! - in com.alibaba.nacos.test.config.ConfigAPI_CITCase
nacos_addListener_1(com.alibaba.nacos.test.config.ConfigAPI_CITCase)  Time elapsed: 25.032 sec  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 25000 milliseconds
	at com.alibaba.nacos.test.config.ConfigAPI_CITCase.nacos_addListener_1(ConfigAPI_CITCase.java:372)
```

**Comment by KomachiSion** [comment]
@ljhrot Can you tell me your ding talk number?

**Comment by ljhrot** [comment]
Sorry! I was too busy today, now I can reply to github notifications in time. 
😎 I abandoned git cli and used IDEA git GUI back.

**Pull request merged**
