### PR TITLE
[ISSUE #9510]Add sql log print function.

### PR DESCRIPTION
**Pull request by The-Gamer-01**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

For issue#9510

## Brief changelog

添加多数据源SQL日志打印功能.

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Comment by li-xiao-shuang** [comment]
1

**Comment by The-Gamer-01** [comment]
现在大概使用JDK动态代理实现了，现在默认是关闭状态，若需要开启，则需要将application.properties中此处注释去掉即可生效；
image

生效效果如下：
image

**Review by li-xiao-shuang — APPROVED** [review]

**Review by KomachiSion — CHANGES_REQUESTED** [review]
Can you add unit test?

**Comment by The-Gamer-01** [comment]
> Can you add unit test?

OK

**Review by li-xiao-shuang — APPROVED** [review]

**Comment by KomachiSion** [comment]
#9510

**Pull request merged**
