### PR TITLE
[ISSUE #10787] Fixed the memory performance issue caused by the creat…

### PR DESCRIPTION
**Pull request by wyt**
…ion of a large number of sessions.

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

XXXXX

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Review by KomachiSion — CHANGES_REQUESTED** [review]
这个改动会不会影响客户端登录时的user name获取？

**Comment by KomachiSion** [comment]
> > 的
> 
> > 客户端
> 
> > 这个改动会不会影响客户端登录时的user name获取？
> 
> l
> 
> > 这个改动会不会影响客户端登录时的user name获取？
> 
> 我自己浏览器和nacos-client测了下，没发现啥问题，内存利用又和1.4.2一样丝滑了。

我印象中这个改动好像是为了解决有slb/nginx之类的负载均衡的时候， 登录失效的问题，改动之后应该对于这个场景又会有问题， 有什么好的版本解决内存问题的时候同时解决这个场景问题吗？

**Comment by wyt** [comment]
这个我还得试验下，但是应该以优先解决内存问题为主。

**Comment by KomachiSion** [comment]
先跑下ci， 没问题就合进去，近期发新版本。

帮忙看下2.x是否有相同的问题，提个PR修复一下。

**Comment by wyt** [comment]
跑失败了嘛，就改了两行代码

**Comment by KomachiSion** [comment]
check style没有过

**Comment by wyt** [comment]
我处理下

**Comment by wyt** [comment]
处理了

**Pull request merged**
