### PR TITLE
Update Header.js

### PR DESCRIPTION
**Pull request by GuoHyan**
优化nacos中文用户登录后主页header显示的中文账号乱码问题。

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

XXXXX

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Comment by GuoHyan** [comment]
优化nacos中文用户登录后主页header显示的中文账号乱码问题

**Review by KomachiSion — APPROVED** [review]

**Comment by KomachiSion** [comment]
Please sign CLA first

**Review by KomachiSion — CHANGES_REQUESTED** [review]
Please sign CLA first

**Comment by KomachiSion** [comment]
Sorry @GuoHyan, the CLA is not fixed. So we can't merge this pr.

**Comment by caojiele** [comment]
> Sorry @GuoHyan, the CLA is not fixed. So we can't merge this pr.

@i will solve it@

**Comment by GuoHyan** [comment]
怎么签署CLA啊

**Comment by GuoHyan** [comment]
CLA已经签署，是否可以重新审核，合并！

**Comment by GuoHyan** [comment]
CLA已经签署，是否可以重新审核，合并！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "杨翊 ***@***.***&gt;; 
发送时间: 2021年6月9日(星期三) 上午10:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/nacos] Update Header.js (#6011)






请先签 CLA

—
您正在接收此消息，因为您创建了该线程。
直接回复此邮件，在 GitHub 上查看或取消订阅.

**Comment by GuoHyan** [comment]
现在CLA已经授权了，是否可以合并我提交的代码



---Original---
From: "Kamran ***@***.***&gt;
Date: Fri, Jun 18, 2021 16:42 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [alibaba/nacos] Update Header.js (#6011)




  
Sorry @GuoHyan, the CLA is not fixed. So we can't merge this pr.
  
@i will solve it@

**Comment by GuoHyan** [comment]
您好，之前我提交的合并head.js里关于中文登录乱码的代码才发现被人合并了，因为第一次在github上贡献代码，不懂怎么操作，也好久没看邮件错过了固定cla，现在固定了cla去却发现已经别人看见我提交的代码以他的名义合并了。但是我才是最初的贡献者啊！这个可以把我加上吗？



---Original---
From: "杨翊 ***@***.***&gt;
Date: Thu, Jun 17, 2021 19:20 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [alibaba/nacos] Update Header.js (#6011)




 
Closed #6011.

**Review by GuoHyan — COMMENTED** [review]
优化header中文账号乱码显示问题

**Pull request closed without merging**
