### PR TITLE
[ISSUE#11679]  when push fail the totalpush count cannot increase

### PR DESCRIPTION
**Pull request by peachisai**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

fix ```totalpush``` cannot increase count when push fail 

## Brief changelog
fix ```totalpush``` cannot increase count when push fail 

## Verifying this change

image

Follow this checklist to help us incorporate your contribution quickly and easily:

* [x] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [x] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Comment by KomachiSion** [comment]
Please  fix your commit user&email and then sign your CLA first.

**Comment by peachisai** [comment]
> Please fix your commit user&email and then sign your CLA first.

May I ask a question? I had already sent the sign CLA mail to the ```[opensource@alibaba-inc.com](mailto:opensource@alibaba-inc.com)``` ,But there is no reply.

**Comment by KomachiSion** [comment]
you git commit user or email is not equal github id `peachisai` or email on your github.

so github think the pr has one commit not sign CLA.

**Comment by KomachiSion** [comment]
You should setting git config user.name and user.email before your submit commits.

I think you should checkout new branch from `develop` and do same changes in new branch, and setting git config user.name and user.email before you commit changes and submit new PR.

**Comment by peachisai** [comment]
> You should setting git config user.name and user.email before your submit commits.
> 
> I think you should checkout new branch from `develop` and do same changes in new branch, and setting git config user.name and user.email before you commit changes and submit new PR.

Thanks for your advice ,I think I understand

**Pull request closed without merging**
