### PR TITLE
[ISSUE #12207] fix disk failover datasource not keep status

### LINKED ISSUE #12207: [bug]disk failover datasource not keep status
**Describe the bug**
I try to use client discovery  feature "failover on disk ", when create failover switch file `00-VIP-SWICH-...`. 

The client log print `failover-mode is on`,  a few second later, log print `failover switch changed, new: off`

Because in DiskFailoverDataSource,  switch file is not change, so lastModifiedMillis == modified and `return new FailoverSwitch(Boolean.FALSE);`

I think this is bug in early pr, i will fix it.

**Expected behavior**
expect failover switch is alway on 

**Actually behavior**
failover switch is off at last

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

### PR DESCRIPTION
**Pull request by shalk**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

fix #12207

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Comment by KomachiSion** [comment]
has `switchParams` keep the status?

**Comment by KomachiSion** [comment]
Suggest submit issue first to describe this problem.

**Comment by shalk** [comment]
> has `switchParams` keep the status?

No, it is not.

 lastmodify is not changed. but the `if` make not it return false

**Comment by KomachiSion** [comment]
> > has `switchParams` keep the status?
> 
> No, it is not.
> 
> When lastmodify is not changed, but `if (lastModifiedMillis < modified)` make FailoverFileReader return false

If lastmodify is not changed, the FailoverFileReader should be false.

**Review by KomachiSion — APPROVED** [review]

**Pull request merged**
