### PR TITLE
fix #5909 problem

### LINKED ISSUE #5909: nacos2.01 config ldap error
Nacos version 2.01 is configured with LDAP integration. Unable to log in after configuration. Logs report no error output
The documentation on the official website does not find any more description of the LDAP configuration, as well as the configuration of the LDAP administration user and password
The LDAP configuration has no problems integrating with other systems

The configuration file is as follows：
image
Login error
image

### PR DESCRIPTION
**Pull request by andotorg**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

add error log print 

fix https://github.com/alibaba/nacos/issues/5909

## Brief changelog

add error log print 

## Verifying this change

print error log

Follow this checklist to help us incorporate your contribution quickly and easily:

* [√ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [√ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [√ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [√ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Comment by KomachiSion** [comment]
Please fix your CLA first

**Comment by andotorg** [comment]
ok

**Comment by KomachiSion** [comment]
Sorry @andotorg , The CLA still not be fixed. So I will close this PR. If you want to submit again, please fix the git log and sign CLA .

**Comment by andotorg** [comment]
We are negotiating and signing. May I leave the name of the company blank?

**Pull request closed without merging**
