### PR TITLE
Develop issue#8906

### PR DESCRIPTION
**Pull request by liushaoyu-soft**
[ISSUES#8906]Exception 'java.io.IOException' is never thrown in the method

### CODE REVIEW

**Review by KomachiSion — CHANGES_REQUESTED** [review]
Why can't throw IOException?

**Comment by liushaoyu-soft** [comment]
> Why can't throw IOException?

An IOException has been catch，so throws IOException Is invalid
image

**Review by KomachiSion — COMMENTED** [review]
[MD5Utils.java](https://github.com/alibaba/nacos/pull/8909/files#diff-81303b2b1f7653a59064150c071883f123614e6a5f22d3f9a165eb6efe1bf232)

I remember you has submit in other PR, Can you rebase on develop branch and re-push your commit?

**Comment by liushaoyu-soft** [comment]
> I remember you has submit in other PR, Can you rebase on develop branch and re-push your commit?
okay, got it

**Pull request closed without merging**
