### PR TITLE
[ISSUE #12342]: Improve the retrieval of ConfigInfoState to facilitate the extension and implementation of databases like Oracle.

### LINKED ISSUE #12342: The implementation of findConfigInfoState is not wrapped through MapperManager
**Describe the bug**
When implementing extension plugins for databases like Oracle, errors occur during the modification of configurations in the public namespace. This is because the implementation of `ExternalConfigInfoPersistServiceImpl#findConfigInfoState` uses hardcoded SQL instead of being wrapped through `MapperManager`.

**Expected behavior**
wrapped through `MapperManager`

### PR DESCRIPTION
**Pull request by gongycn**
## What is the purpose of the change
fixes #12342 
Improve the retrieval of ConfigInfoState to facilitate the extension and implementation of databases like Oracle.

## Brief changelog
Generate the SQL required by `ExternalConfigInfoPersistServiceImpl#findConfigInfoState` using the `select` method from `MapperManager`.

## Verifying this change
We have already used this method in the production environment, adapting the configuration management for both Oracle and MySQL databases.

### CODE REVIEW

**Review by mhdifarahani — COMMENTED** [review]
yeah

**Comment by KomachiSion** [comment]
Can you add unit test for this?

**Comment by gongycn** [comment]
> Can you add unit test for this?

The SQL construction logic of the `ExternalConfigInfoPersistServiceImpl#findConfigInfoState` method has been modified. Therefore, a `testBuildFindConfigInfoStateSql` method was added to the `ExternalConfigInfoPersistServiceImplTest` to handle unit testing for the SQL construction part.

**Comment by KomachiSion** [comment]
I see the CLA has no signed.

Can you sign the CLA?

**Review by KomachiSion — DISMISSED** [review]

**Comment by gongycn** [comment]
> I see the CLA has no signed.
> 
> Can you sign the CLA?

CLA has been signed.

**Comment by gongycn** [comment]
@KomachiSion Could this change be merged? Thank you.

**Review by mhdifarahani — COMMENTED** [review]
I like this. I think it true

**Review by mhdifarahani — COMMENTED** [review]
@[www.FarahanTechnical.com](url)

**Review by KomachiSion — APPROVED** [review]

**Pull request merged**
