### PR TITLE
[#6178] Unified configuration page style

### PR DESCRIPTION
**Pull request by zzq1314zll**
Unified configuration page style

For #6178

### CODE REVIEW

**Comment by KomachiSion** [comment]
There are many changes, can you create an issue first to describe why you want to change this?

**Comment by zzq1314zll** [comment]
Only button style and form style

**Comment by zzq1314zll** [comment]
This #6178

**Comment by realJackSun** [comment]
fix #6278

**Review by KomachiSion — APPROVED** [review]

**Pull request merged**
