### PR TITLE
remove serverList initialization as self address is always added to serverList at memberChange()

### LINKED ISSUE #5240: com.alibaba.nacos.core.cluster.MemberUtilTest的setUp里的await建议加个超时设置
**Describe the solution you'd like**
这个项目自动构建目前大概率会失败，总是在com.alibaba.nacos.core.cluster.MemberUtilTest测试方法hang掉。原因我没去查，因为本机测试没有出现这个问题。

**Describe alternatives you've considered**
latch.await();这行代码建议改一下，加个超时控制，免得一直等。

### PR DESCRIPTION
**Pull request by zrlw**
## What is the purpose of the change
fix #5240

### CODE REVIEW

**Review by KomachiSion — CHANGES_REQUESTED** [review]
Maybe publish a member change event is better. Otherwise, the add self will not be notified.

**Comment by zrlw** [comment]
> Maybe publish a member change event is better. Otherwise, the add self will not be notified.

keep serverlist empty before calling initAndStartLookup will publish a member change event.

**Review by KomachiSion — CHANGES_REQUESTED** [review]
self should be add to server list always to ensure that after usage can get self.

**Comment by zrlw** [comment]
> self should be add to server list always to ensure that after usage can get self.

the function memberChange is always called in initialization, self is always  added to server list even you don't add it explicitly.

**Comment by KomachiSion** [comment]
I read the issue, and I found the problem is not in add self to list, the reason is that the Test case error.

In my opinion, when init, add self to list is a necessary operation, and the updateMembers add self is a protection operation. So no problem for this two codes.

In some case, for example, standalone or cluster but only one node, which means the server list after add self is same as read from loopUp, so it is no need to notified changed event, which also is right.

So I think solve problem should to fix the Test case.

**Comment by zrlw** [comment]
> I read the issue, and I found the problem is not in add self to list, the reason is that the Test case error.
> 
> In my opinion, when init, add self to list is a necessary operation, and the updateMembers add self is a protection operation. So no problem for this two codes.
> 
> In some case, for example, standalone or cluster but only one node, which means the server list after add self is same as read from loopUp, so it is no need to notified changed event, which also is right.
> 
> So I think solve problem should to fix the Test case.

restarting standalone or one node cluster might also mean a change event, as least server startup time changed.

**Comment by KomachiSion** [comment]
So maybe we need focus two question:

Whether member add self need send an event when init. 
And how to enhance the test case.

**Review by Moskalnazar — APPROVED** [review]

**Review by Moskalnazar — COMMENTED** [review]
Thank you!

**Review by Moskalnazar — COMMENTED** [review]
good

**Pull request closed without merging**
