### PR TITLE
[ISSUE #7359] Add xss filter

### LINKED ISSUE #7359: This is  XSS vulnerabilities
Nacos has xss vulnerability

Trigger condition: no verification required

version: Nacos 2.0.3

payload1:`/nacos/v1/auth/users?pageNo=1&pageSize=<script>alert(1)</script>`
payload2:`/nacos/v1/auth/users?pageNo=<script>alert(1)</script>&pageSize=1`

image
image

### PR DESCRIPTION
**Pull request by onewe**
- Set response header 'Content-Security-Policy'

Close #7359 

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

xxx

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [x] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [x] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Review by KomachiSion — CHANGES_REQUESTED** [review]
Has you test the feature of nacos and prometheus actuator?

I used to add similar filter, but the response data like config and prometheus actuator will be translated and the client and exporter can't understand the response.

**Comment by onewe** [comment]
I haven't tested it yet, It's only to add a http header,Don't it only effect the browsers? @KomachiSion

**Comment by KomachiSion** [comment]
openAPI maybe used by sdk or other users. prometheus metrics also be effected.

**Comment by onewe** [comment]
Ok, I will test it.

**Comment by onewe** [comment]
I have tested it,I think it doesn't effect Prometheus or etc. Could you try it and give me a feedback.
image
image

**Review by KomachiSion — APPROVED** [review]

**Comment by onewe** [comment]
@biubiue https://github.com/alibaba/nacos/pull/8980 1.4.5

**Comment by onewe** [comment]
1.4.1？？ There is not the `xssFilter` in this version, the filter has been mergered into the v1.x-develop(#8980) branch currently. May be released on v1.4.5

@lovelynewer

**Comment by lovelynewer** [comment]
> 1.4.1？？ There is not the `xssFilter` in this version, the filter has been mergered into the v1.x-develop(#8980) branch currently. May be released on v1.4.5
> 
> @lovelynewer

I have a try and it finally worked,thank you very much.

**Pull request merged**
