### PR TITLE
Fix issue#{7096}

### PR DESCRIPTION
**Pull request by SteafanMrZhou**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

Fix issue#{7096},Fix the problem.

### CODE REVIEW

**Comment by SteafanMrZhou** [comment]
#7096

**Comment by SteafanMrZhou** [comment]
@realJackSun

**Comment by KomachiSion** [comment]
There are conflicts.

**Comment by KomachiSion** [comment]
No more response from author, and this PR has conflict.

**Pull request closed without merging**
