### PR TITLE
[#3388]Remove the deleted roles and permissions info during reloading role info

### PR DESCRIPTION
**Pull request by yanjunnf**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

#3388

## Brief changelog
We should remove these already deleted roles, permissions during reloading nacos role info.

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Comment by yanjunnf** [comment]
Why do not clear roleSet, roleInfoMap and permissionInfoMap before putAll/addAll?
The clear method cannot provide the whole logic as a atomic operation.
For example, roleSet.clear() finished to execute, but now this thread is suspended, then antoher thread try to get all roles, it will get a empty list since the roleSet object was cleared.

**Comment by yanjunnf** [comment]
license/cla Pending — Contributor License Agreement is not signed yet.
I really signed several times, but this message still shows.

**Comment by KomachiSion** [comment]
> license/cla Pending — Contributor License Agreement is not signed yet.
> I really signed several times, but this message still shows.

The reason is your git username and email is not your github id.
So the git commit log author is junyan29, but you signed CLA is for yanjunnf.

It's different.

Solution is to set the git username and email to your github id.

Search in search engine, you can get many answer.

**Comment by KomachiSion** [comment]
And for the PR content, I describe in PR before you submit.

Why don't clear all map and then putAll again, but to remove one by one. I think the new put is all data for users and permissions.

**Comment by yanjunnf** [comment]
> And for the PR content, I describe in PR before you submit.
> 
> Why don't clear all map and then putAll again, but to remove one by one. I think the new put is all data for users and permissions.
> 
> @chuntaojun Is my understanding correct?

The clear method cannot guarantee the whole logic as a atomic operation.
For example, roleSet.clear() finished to execute, but at this time, this thread is suspended, then antoher thread try to get all roles, it will get a empty list since the roleSet object was cleared, that may cuase the empty role/permission list showes on UI part.
Remove one by one, that can reduce impaction.

**Comment by chuntaojun** [comment]
I think this is too complicated, but logically, there are only reads to the map, not writes. You can take advantage of the volatile property, replace the application directly, and then destroy the old Map

**Comment by KomachiSion** [comment]
I agree with @chuntaojun, if you think about the thread safe, you can use a tmp map/set to save new data from persistence, and directly replace them.

**Comment by KomachiSion** [comment]
Once more about the CLA, I check your commit log, it contain many `merge branch`, I recommend that you use rebase to squash them. And if there are still `junyan29`'s commit. I think you should revert them and re commit with `yanjunnf`

**Comment by yanjunnf** [comment]
Thanks for your reply.
Yes， I agree with you in priciple about keeping the code clean and simple.
I though about to use tmp object and replace, If that we have to remove “final “ modifier for class members roleSet, roleInfoMap and permissionInfoMap.

**Comment by KomachiSion** [comment]
If there map/set need to be reset, remove `final` will be ok. @chuntaojun What's your idea?

**Comment by chuntaojun** [comment]
agree

发自我的iPhone

在 2020年7月24日，17:03，杨翊 SionYang <notifications@github.com> 写道：

﻿

If these map/set need to be reset, remove final will be ok. @chuntaojun<https://github.com/chuntaojun> What's your idea?

**Comment by yanjunnf** [comment]
Closed it and recreate a new PR([#3388]Reset nacos roles, permissions during reloading role info from database) to fix issue 3388 since CLA problem.

**Pull request closed without merging**
