### PR TITLE
Nacos+MySQL8 startup error

### PR DESCRIPTION
**Pull request by paderlol**
## Issue: 
#852 #613 

## The solution
Use class.forname to determine which version of the database driver to use，And Use Class.forName to determine which version of the database driver to use, and put the driver Jar in the **plugins** directory. By default, use `mysql-connector-java-5.1.34.jar`.

## Good point
* The expansion of other types of database-driven to become more flexible,You just need to put the database driver you want to use in it. eg. Mysql 8.0/Oracle

## Usage
If you need to use the Mysql 8.0 database, you can put Mysql 8.0 database driver on xx/nacos/plugins/mysql Directory

### CODE REVIEW

**Review by yanlinly — APPROVED** [review]
ok
Please add design documents and usage documents.

**Comment by quzhixue-Kimi** [comment]
Hi there,

Currently, does Nacos Version 1.0.0 support mysql 8 or not?

I followed the suggestion to put the mysql-connector-java-8.0.15.jar into the folder of /nacos/plugins/mysql but, there is one issue occurred when I modify my configuration and publish in Nacos.
The message is java.sql.SQLException: Unknown system variable 'tx_read_only'
It is appreciated that any feedback or suggestion could be provided.

BR
Kimi

**Comment by wowtrxqn** [comment]
If you need to use the Mysql 8.0 database, you can put Mysql 8.0 database driver on xx/nacos/plguins/mysql Directory

it seems not be work。
at least test failed In my window environment。
In the DIngDing nacos talking-group of more than 2,000 people, I asked a day of questions about mysql8, no one help solved。

**Comment by duwei54** [comment]
I meet the same issue. My environment is:
win10
mysql 8.0.11
nacos 1.0

**Comment by wowtrxqn** [comment]
> I meet the same issue. My environment is:
> win10
> mysql 8.0.11
> nacos 1.0

succeed in linux, error in win10

**Comment by duwei54** [comment]
I solved my problem by change the mysql config `character_set_server` to utf8.
I set it to utf8mb4 after mysql installed.but it seems not be supported.

**Comment by LOpSSH** [comment]
This solution doesn't work on Windows.

**Comment by LOpSSH** [comment]
By checking code of yours, I found a definitive error as pasted below : 
`%BASE_DIR%\plugins\cmdb:%BASE_DIR%\plugins\mysql` < a semicolon but not colon should be used here.

**Comment by LOpSSH** [comment]
This doesn't work on Windows. :broken_heart: 
By checking that code, I found a definitive error as pasted below :
`%BASE_DIR%\plugins\cmdb:%BASE_DIR%\plugins\mysql` < a semicolon instead of a colon should be used.
Again, this error still exists.

**Comment by firstLeon** [comment]
> 我遇到同样的问题。我的环境是：
> win10 
> mysql 8.0.11 
> nacos 1.0

我在set "JAVA_OPT=%JAVA_OPT% -Dloader.path这里加上%BASE_DIR%\plugins\mysql解决了

**Pull request merged**
