### PR TITLE
[ISSUE #5475] enhance the rollback message when it will delete the config.

### LINKED ISSUE #5475: [Enhancement] Configuration rollback add hint.
**Is your feature request related to a problem? Please describe.**
When the configuration is rolled back, the configuration will be deleted if the operation type is insert, users will feel a little confused. I think a hint can be added, like this: 
image
Refer to : #4064 , #2731 ,#5358
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by brothelul**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

Fixes #5475 
Enhance the rollback message when it will delete the config.

## Brief changelog

XX

## Verifying this change
the rollback will update the config will keep as before.
the rollback will delete config will show as below.
In English:
image

In Chinese:
image

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Review by haoyann — DISMISSED** [review]
LGTM

**Comment by KomachiSion** [comment]
Preparing release 1.4.2 and pending PR temparately.

**Comment by KomachiSion** [comment]
@brothelul main.js seems has conflict. Can you fix it?

**Comment by brothelul** [comment]
OK，I will fix it.

**Review by KomachiSion — APPROVED** [review]

**Comment by KomachiSion** [comment]
@brothelul Can you submit a new PR for 2.0.X to branch feature_support_grpc_core?

**Pull request merged**
