### PR TITLE
[ISSUE #8407] Remove whitespace

### LINKED ISSUE #8407: Ldap config 多了一个空格
image

### PR DESCRIPTION
**Pull request by Oliverwqcwrw**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

- Close #8407 
- Fix circular dependency
- Fix failed UT

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [x] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Review by karsonto — DISMISSED** [review]

**Comment by Oliverwqcwrw** [comment]
> I also have the same problem with PR#8398

Can you find the problem?

**Comment by karsonto** [comment]
Sorry,I have no idea with this problem.

**Comment by Oliverwqcwrw** [comment]
Our problem is same, I have a case where I can reproduce this problem by running all the unit tests of` config-test` under `nacos-test`, and then running all the unit tests of `naming-test`

**Comment by KomachiSion** [comment]
Please rebase `develop` branch, we have fixed the CI and IT problem.

**Review by KomachiSion — APPROVED** [review]

**Pull request merged**
