### PR TITLE
sync to istio. instance port customize

### PR DESCRIPTION
**Pull request by siaron**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

#7268

## Brief changelog

- sync to istio. instance port customize

## Verifying this change

- meatadata add 'istio.port=xxx' verify

Follow this checklist to help us incorporate your contribution quickly and easily:

* [x] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [x] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Comment by siaron** [comment]
https://github.com/alibaba/nacos/issues/7268

**Review by SpecialYang — CHANGES_REQUESTED** [review]
Sorry for the late code review. We should figure out a common way to fix the similar issues.

**Review by realJackSun — APPROVED** [review]

**Review by KomachiSion — CHANGES_REQUESTED** [review]
> Sorry for the late code review. We should figure out a common way to fix the similar issues.

**Review by realJackSun — CHANGES_REQUESTED** [review]
这个port修改应该需要统一做一下规范化，设计成通用方案

**Comment by realJackSun** [comment]
@SpecialYang please take care of this when you have time.

**Comment by siaron** [comment]
有什么实现思路吗? 如何通用?

**Comment by KomachiSion** [comment]
CLA no signed for a long time.

**Pull request closed without merging**
