### PR TITLE
[ISSUE #3370] Issue with executing shell script /bin/sh^M on Unix/Linux

### PR DESCRIPTION
**Pull request by Veryfirefly**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

1. Fixed the /bin/sh^M problem when executing startup.sh and shutdown.sh scripts on Linux.
2. Fixed the following problems when performing binary packaging: `ERROR OS = Windows, and the assembly descriptor contains *nix specific root-relative-reference`

## Brief changelog

<table style="border-collapse: collapse;">
    <tr>
	  <td>Path</td>
	  <td>Change</td>
	</tr>
    <tr>
	  <td>nacos/distribution/bin/startup.sh</td>
	  <td>CRLF -> LF</td>
	</tr>
    <tr>
	  <td>nacos/distribution/bin/shutdown.sh</td>
	  <td>CRLF -> LF</td>
	</tr>
    <tr>
	  <td>nacos/distribution/release-nacos.xml</td>
	  <td>nacos-server/outputDirectory</td>
	</tr>
</table>

### CODE REVIEW

**Comment by KomachiSion** [comment]
1. I check the develop branch, the four bin files is `LF` already. I think we have no need to change.
2. the `nacos-server/outputDirectory`, It has been able to run well, I do not know why it needs to be modified.

**Comment by Veryfirefly** [comment]
> 1. I check the develop branch, the four bin files is `LF` already. I think we have no need to change.
> 2. the `nacos-server/outputDirectory`, It has been able to run well, I do not know why it needs to be modified.

The `nacos-server/outputDirectory`,  The following error occurs when packaging: `[ERROR] OS=Windows and the assembly descriptor contains a *nix-specific root-relative-reference (starting with slash) /target/`. But this does not affect the packaging. This will give the developer an error message, similar to warning

 I queried the documentation and found that the reason is: because the assembly task is executed on Windows, but it contains a path relative to Linux. The document states that `outputDirectory` defines a `/` which would in consequence mean to extract all contens to always same location.

This is my image when packing
OS=Windows

**Comment by KomachiSion** [comment]
My env is MacOs, has no error. 

Can someone in the community help to confirm whether this change can eliminate the error message and be packaged correctly?

**Comment by Veryfirefly** [comment]
> My env is MacOs, has no error.
> 
> Can someone in the community help to confirm whether this change can eliminate the error message and be packaged correctly on windows OS?

Ok i am looking for help

**Comment by zongtanghu** [comment]
image

**Comment by zongtanghu** [comment]
I have already verified this in my local windows enviroment.The result is as above.

**Comment by zongtanghu** [comment]
And If no anything modified, the result is as below:

image

**Comment by Veryfirefly** [comment]
> And If no anything modified, the result is as below:
> 
> image

Thanks for help

**Pull request merged**
