### PR TITLE
fix(#11930): the information of default namespace should be consistent.

### PR DESCRIPTION
**Pull request by Bo-Qiu**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

fix(#11930 ): the information of default namespace should be consistent.

## Brief changelog

fix(#11930 ): the information of default namespace should be consistent.

## Verifying this change

fix(#11930 ): the information of default namespace should be consistent.

### CODE REVIEW

**Comment by KomachiSion** [comment]
说起这个， 我感觉这个值可能要改一下来着，

showname 大家应该更习惯小写吧 `public` 毕竟很久了， 突然改成 `Public` 可能不如改成 `public` 好接受。

至于desc，我觉得可以改成`Default Namespace`

**Comment by Bo-Qiu** [comment]
> 说起这个， 我感觉这个值可能要改一下来着，
> 
> showname 大家应该更习惯小写吧 `public` 毕竟很久了， 突然改成 `Public` 可能不如改成 `public` 好接受。
> 
> 至于desc，我觉得可以改成`Default Namespace`

有道理，我调整下。

**Comment by wuyfee** [comment]
$\color{red}{FAILURE}$
[DETAILS](https://github.com/alibaba/nacos/actions/runs/11661655687)
 ✅ - docker:   success 
 ✅ - deploy (standalone & cluster & standalone_auth):   success 
 ✅ - e2e-java-test (standalone & cluster & standalone_auth):   success 
 ✅ - e2e-go-test (standalone & cluster):   success 
 ✅ - e2e-cpp-test (standalone & cluster):   success 
 ❌ - e2e-csharp-test (standalone & cluster):   failure 
 ✅ - e2e-nodejs-test (standalone & cluster):   success 
 ✅ - e2e-python-test (standalone & cluster):   success 
 ✅ - clean (standalone & cluster & standalone_auth):   success

**Comment by wuyfee** [comment]
$\color{green}{SUCCESS}$
[DETAILS](https://github.com/alibaba/nacos/actions/runs/11661715795)
 ✅ - docker:   success 
 ✅ - deploy (standalone & cluster & standalone_auth):   success 
 ✅ - e2e-java-test (standalone & cluster & standalone_auth):   success 
 ✅ - e2e-go-test (standalone & cluster):   success 
 ✅ - e2e-cpp-test (standalone & cluster):   success 
 ✅ - e2e-csharp-test (standalone & cluster):   success 
 ✅ - e2e-nodejs-test (standalone & cluster):   success 
 ✅ - e2e-python-test (standalone & cluster):   success 
 ✅ - clean (standalone & cluster & standalone_auth):   success

**Comment by wuyfee** [comment]
$\color{green}{SUCCESS}$
[DETAILS](https://github.com/alibaba/nacos/actions/runs/11661680406)
 ✅ - docker:   success 
 ✅ - deploy (standalone & cluster & standalone_auth):   success 
 ✅ - e2e-java-test (standalone & cluster & standalone_auth):   success 
 ✅ - e2e-go-test (standalone & cluster):   success 
 ✅ - e2e-cpp-test (standalone & cluster):   success 
 ✅ - e2e-csharp-test (standalone & cluster):   success 
 ✅ - e2e-nodejs-test (standalone & cluster):   success 
 ✅ - e2e-python-test (standalone & cluster):   success 
 ✅ - clean (standalone & cluster & standalone_auth):   success

**Review by KomachiSion — APPROVED** [review]

**Pull request merged**
