### PR TITLE
Optimize com.alibaba.nacos.client.config.impl.ServerListManager#start to start, reduce the number of initial serverlist initialization

### PR DESCRIPTION
**Pull request by xiaoheng1**
## What is the purpose of the change

see more detail from #5479 

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Comment by TsingLiang** [comment]
for循环中已经有判断了，没有必要加这个

**Comment by xiaoheng1** [comment]
> for循环中已经有判断了，没有必要加这个

我查看了代码：
getServersTask.run() 是对 serverUrls 进行赋值。所以 serverUrls 不为空，也不会退出 for 循环了。


```
GetServerListTask getServersTask = new GetServerListTask(addressServerUrl);
        for (int i = 0; i < initServerlistRetryTimes && serverUrls.isEmpty(); ++i) {
            getServersTask.run();
            // When serverUrls is not empty, skip subsequent blocking directly.
            if (!serverUrls.isEmpty()) {
                break;
            }
            try {
                this.wait((i + 1) * 100L);
            } catch (Exception e) {
                LOGGER.warn("get serverlist fail,url: {}", addressServerUrl);
            }
        }
```

**Comment by KomachiSion** [comment]
> > for循环中已经有判断了，没有必要加这个
> 
> 我查看了代码：
> getServersTask.run() 是对 serverUrls 进行赋值。所以 serverUrls 不为空，也不会退出 for 循环了。
> 
> ```
> GetServerListTask getServersTask = new GetServerListTask(addressServerUrl);
>         for (int i = 0; i < initServerlistRetryTimes && serverUrls.isEmpty(); ++i) {
>             getServersTask.run();
>             // When serverUrls is not empty, skip subsequent blocking directly.
>             if (!serverUrls.isEmpty()) {
>                 break;
>             }
>             try {
>                 this.wait((i + 1) * 100L);
>             } catch (Exception e) {
>                 LOGGER.warn("get serverlist fail,url: {}", addressServerUrl);
>             }
>         }
> ```

那应该修改`i < initServerlistRetryTimes && serverUrls.isEmpty()` 中的条件，而不是在循环中break

**Comment by xiaoheng1** [comment]
> > > for循环中已经有判断了，没有必要加这个
> > 
> > 
> > 我查看了代码：
> > getServersTask.run() 是对 serverUrls 进行赋值。所以 serverUrls 不为空，也不会退出 for 循环了。
> > ```
> > GetServerListTask getServersTask = new GetServerListTask(addressServerUrl);
> >         for (int i = 0; i < initServerlistRetryTimes && serverUrls.isEmpty(); ++i) {
> >             getServersTask.run();
> >             // When serverUrls is not empty, skip subsequent blocking directly.
> >             if (!serverUrls.isEmpty()) {
> >                 break;
> >             }
> >             try {
> >                 this.wait((i + 1) * 100L);
> >             } catch (Exception e) {
> >                 LOGGER.warn("get serverlist fail,url: {}", addressServerUrl);
> >             }
> >         }
> > ```
> 
> 那应该修改`i < initServerlistRetryTimes && serverUrls.isEmpty()` 中的条件，而不是在循环中break

确实是。
抱歉，没有注意到循环条件。我把这个关闭掉。

**Comment by xiaoheng1** [comment]
> > > > for循环中已经有判断了，没有必要加这个
> > > 
> > > 
> > > 我查看了代码：
> > > getServersTask.run() 是对 serverUrls 进行赋值。所以 serverUrls 不为空，也不会退出 for 循环了。
> > > ```
> > > GetServerListTask getServersTask = new GetServerListTask(addressServerUrl);
> > >         for (int i = 0; i < initServerlistRetryTimes && serverUrls.isEmpty(); ++i) {
> > >             getServersTask.run();
> > >             // When serverUrls is not empty, skip subsequent blocking directly.
> > >             if (!serverUrls.isEmpty()) {
> > >                 break;
> > >             }
> > >             try {
> > >                 this.wait((i + 1) * 100L);
> > >             } catch (Exception e) {
> > >                 LOGGER.warn("get serverlist fail,url: {}", addressServerUrl);
> > >             }
> > >         }
> > > ```
> > 
> > 
> > 那应该修改`i < initServerlistRetryTimes && serverUrls.isEmpty()` 中的条件，而不是在循环中break
> 
> 确实是。
> 抱歉，没有注意到循环条件。我把这个关闭掉。

但是如果在循环条件中的话，会多等一个  100 ms，这个是否要修复掉了？

**Comment by KomachiSion** [comment]
> > > > > for循环中已经有判断了，没有必要加这个
> > > > 
> > > > 
> > > > 我查看了代码：
> > > > getServersTask.run() 是对 serverUrls 进行赋值。所以 serverUrls 不为空，也不会退出 for 循环了。
> > > > ```
> > > > GetServerListTask getServersTask = new GetServerListTask(addressServerUrl);
> > > >         for (int i = 0; i < initServerlistRetryTimes && serverUrls.isEmpty(); ++i) {
> > > >             getServersTask.run();
> > > >             // When serverUrls is not empty, skip subsequent blocking directly.
> > > >             if (!serverUrls.isEmpty()) {
> > > >                 break;
> > > >             }
> > > >             try {
> > > >                 this.wait((i + 1) * 100L);
> > > >             } catch (Exception e) {
> > > >                 LOGGER.warn("get serverlist fail,url: {}", addressServerUrl);
> > > >             }
> > > >         }
> > > > ```
> > > 
> > > 
> > > 那应该修改`i < initServerlistRetryTimes && serverUrls.isEmpty()` 中的条件，而不是在循环中break
> > 
> > 
> > 确实是。
> > 抱歉，没有注意到循环条件。我把这个关闭掉。
> 
> 但是如果在循环条件中的话，会多等一个 100 ms，这个是否要修复掉了？
> 
> 循环条件只能等下次才能生效，但是如果 serverUrls 不为空的话，其实 100ms 也是可以省掉的.

这个没有关系，等100ms是说超时100ms， 异步任务会在获取到urls的第一时间notify的。不会阻塞

**Comment by xiaoheng1** [comment]
> > > > > > for循环中已经有判断了，没有必要加这个
> > > > > 
> > > > > 
> > > > > 我查看了代码：
> > > > > getServersTask.run() 是对 serverUrls 进行赋值。所以 serverUrls 不为空，也不会退出 for 循环了。
> > > > > ```
> > > > > GetServerListTask getServersTask = new GetServerListTask(addressServerUrl);
> > > > >         for (int i = 0; i < initServerlistRetryTimes && serverUrls.isEmpty(); ++i) {
> > > > >             getServersTask.run();
> > > > >             // When serverUrls is not empty, skip subsequent blocking directly.
> > > > >             if (!serverUrls.isEmpty()) {
> > > > >                 break;
> > > > >             }
> > > > >             try {
> > > > >                 this.wait((i + 1) * 100L);
> > > > >             } catch (Exception e) {
> > > > >                 LOGGER.warn("get serverlist fail,url: {}", addressServerUrl);
> > > > >             }
> > > > >         }
> > > > > ```
> > > > 
> > > > 
> > > > 那应该修改`i < initServerlistRetryTimes && serverUrls.isEmpty()` 中的条件，而不是在循环中break
> > > 
> > > 
> > > 确实是。
> > > 抱歉，没有注意到循环条件。我把这个关闭掉。
> > 
> > 
> > 但是如果在循环条件中的话，会多等一个 100 ms，这个是否要修复掉了？
> > 循环条件只能等下次才能生效，但是如果 serverUrls 不为空的话，其实 100ms 也是可以省掉的.
> 
> 这个没有关系，等100ms是说超时100ms， 异步任务会在获取到urls的第一时间notify的。不会阻塞

好的，那我把这个关闭掉

**Pull request closed without merging**
