### PR TITLE
[ISSUE #827] Fix Nacos Naming's log settings affect the root log

### LINKED ISSUE #827: Nacos Naming's log settings affect the root log
# Reporting bugs

The log level of Nacos Naming's Logger is set to Debug, but there is no Logger configuration named "com.alibaba.nacos.client.naming", which will cause the "Root" log level to be also set to Debug.

[LogUtils.java#L45](https://github.com/alibaba/nacos/blob/develop/client/src/main/java/com/alibaba/nacos/client/naming/utils/LogUtils.java#L45)

### PR DESCRIPTION
**Pull request by Summerslyb**
## What is the purpose of the change

Fix #827 with a better solution. 
The current solution will ignore some configurations if you don't use the default configuration location to configure or you add some custom configurations after loading the configuration file.

## Brief changelog

- After inserting Nacos `NAMING_LOGGER`, it will recover the Log4j2 context configuration.
- Remove useless `findConfig()` and related classes and methods. 

## Verifying this change

Follow this checklist to help us incorporate your contribution quickly and easily:

* [x] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [x] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Comment by hxy1991** [comment]
The Nacos client defines its own log configuration, which is different from the log configuration of the upper application.

The reason why the code is processed is to load both the Nacos client's own Log4j2 log configuration (nacos-log4j2.xml) and the upper application's Log4j2 configuration file (such as log4j.xml).

According to your modification, the Log4j2 configuration file of the upper application cannot be loaded.

**Comment by Summerslyb** [comment]
> The Nacos client defines its own log configuration, which is different from the log configuration of the upper application.
> The reason why the code is processed is to load both the Nacos client's own Log4j2 log configuration (nacos-log4j2.xml) and the upper application's Log4j2 configuration file (such as log4j.xml).
> According to your modification, the Log4j2 configuration file of the upper application cannot be loaded.

The upper configuration information has already included in the `loggerContext.getConfiguration();`.
Usually, Log4j2 will be initialized much more earlier than nacos.

**Comment by hxy1991** [comment]
"CompositeConfiguration" is a combination of child nodes of the same type in "AbstractConfiguration". The call stack is as follows:

```
Log4J2NacosLogging.loadConfiguration:85
// log4j 2.7
LoggerContext.start:258 
LoggerContext.setConfiguration:530
AbstractConfiguration.start:239
AbstractConfiguration.initialize:225
CompositeConfiguration.setup:120
DefaultMergeStrategy.mergConfigurations:154
```

Calling LogManager.getContext will initialize the Log4j2 configuration of the upper application (such as log4j2.xml), which will clear the child nodes. The call stack is as follows:

```
Log4J2NacosLogging.loadConfiguration:66 
// log4j 2.7
LoggerContext.start:226
LoggerContext.setConfiguration:530
AbstractConfiguration.start:239
PluginElementVisitor.visit:79 // node.getChildren().removeAll(used);
```

According to your modification, the child node of the upper application's Log4j2 configuration has been cleared, and finally only the Nacos Client's Log4j2 takes effect in the "CompositeConfiguration".

**Comment by Summerslyb** [comment]
Well, I found some mistake when two `XMLConfiguration` are merged. My implementation is not suitable for all kinds of configuration.

I will try to add loggers and appenders programmatically tomorrow. Should I reopen a new PR or append new commits to the current PR?

**Comment by nkorange** [comment]
> Well, I found some mistakes when two `XMLConfiguration` are merged. My implementation is not suitable for all kinds of configuration.
> 
> I will try to add loggers and appenders programmatically tomorrow. Should I reopen a new PR or append new commits to the current PR?

If your new commits are to solve the same problem of issue #827, you can just append commits to this PR.

**Comment by Summerslyb** [comment]
Remove odd commits and add new commits.

**Pull request merged**
