### PR TITLE
[ISSUE #6216] Unify SQL naming style.

### PR DESCRIPTION
**Pull request by mask616**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

For [#6216]

Unify SQL naming style.
### Naming rules:
**SQL keyword : uppercase(eg.INSERT INTO, SELECT, UPDATE, DELETE, FROM, WHERE, LEFT JOIN, AND, LIKE... )**
**SQL function name : lowercase(eg. count, max...)**
**SQL field name: lowercase**
**Table name : lowercase**

### For  example: 
`SELECT  a,b,c FROM table;`
`SELECT count(*) FROM table;`

### CODE REVIEW

**Comment by KomachiSion** [comment]
Is this PR duplicated with #6233？

**Comment by mask616** [comment]
> #6233？

No, #6233 just modified the naming of some java source files SQL. This PR unifies the naming of all Java source files SQL in the config module. In addition, I also provide naming rules.But there may be conflicts.

**Review by KomachiSion — CHANGES_REQUESTED** [review]
I found that the `count` is modified by other PR to upper case.

And all of them are modified to lower case. 

Should we unify al of them?

**Comment by mask616** [comment]
> I found that the `count` is modified by other PR to upper case.
> 
> And all of them are modified to lower case.
> 
> Should we unify al of them?

Now, all the `count` is lower case.

**Review by KomachiSion — APPROVED** [review]

**Pull request merged**
