### PR TITLE
[ISSUE#12074] Add Python sample for nacos

### PR DESCRIPTION
**Pull request by CallMeHFK**
## What is the purpose of the change

#12074  Add Python sample for nacos

## Brief changelog

The service is automatically connected to Nacos based on Python, and the service is self-registered

## Verifying this change
XXXX

## Follow this checklist to help us incorporate your contribution quickly and easily:

 Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
 Format the pull request title like . Each commit in the pull request should have a meaningful subject line and body.[ISSUE #123] Fix UnknownException when host config not exist
 Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
 Run to make sure basic checks pass. Run to make sure unit-test pass. Run to make sure integration-test pass.mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=truemvn clean install -DskipITsmvn clean test-compile failsafe:integration-test

### CODE REVIEW

**Comment by KomachiSion** [comment]
Sorry， the issue means add python example code in nacos console， not in nacos exmaple module。

**Comment by CallMeHFK** [comment]
@KomachiSion You means put it here ?
image

**Review by CallMeHFK — COMMENTED** [review]
Need nacos group developer to check this

**Comment by KomachiSion** [comment]
> @KomachiSion You means put it here ? image

Yes

**Review by KomachiSion — APPROVED** [review]

**Review by CallMeHFK — COMMENTED** [review]
Merged, @KomachiSion should I close this issue by myself?

**Pull request merged**
