### PR TITLE
[ISSUE #4025]Nacos support decrypt acm kms config

### PR DESCRIPTION
**Pull request by lidaoyang**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

Nacos support decrypt acm kms config

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [x] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Comment by chuntaojun** [comment]
This dependent on ali cloud related dependencies, I think can not be merged

**Comment by lidaoyang** [comment]
> This dependent on ali cloud related dependencies, I think can not be merged
Because the encryption configuration in ACM is encrypted through Alibaba Cloud KMS service, it depends on the Alibaba Cloud sdk.
因为ACM 中的加密配置是通过阿里云KMS服务加密的，所以需要依赖阿里云的sdk

**Comment by lidaoyang** [comment]
> This dependent on ali cloud related dependencies, I think can not be merged

Because the encryption configuration in ACM is encrypted through Alibaba Cloud KMS service, it depends on the Alibaba Cloud sdk.
因为ACM 中的加密配置是通过阿里云KMS服务加密的，所以需要依赖阿里云的sdk

**Comment by chuntaojun** [comment]
By that I mean that the open source nacos should not be coupled to any cloud vendor dependency

**Comment by chuntaojun** [comment]
When the configuration encryption plug-in is designed, Alibaba Cloud's encryption is introduced as one of the encryption plug-ins. At present, I personally cannot agree to this implementation.

**Comment by lidaoyang** [comment]
> When the configuration encryption plug-in is designed, Alibaba Cloud's encryption is introduced as one of the encryption plug-ins. At present, I personally cannot agree to this implementation.

What you said is correct. Is there a detailed plan on how to realize it?
你说的是对的，具体怎么实现有详细的计划么？

**Comment by liangyuanpeng** [comment]
> > When the configuration encryption plug-in is designed, Alibaba Cloud's encryption is introduced as one of the encryption plug-ins. At present, I personally cannot agree to this implementation.
> 
> What you said is correct. Is there a detailed plan on how to realize it?
> 你说的是对的，具体怎么实现有详细的计划么？

Maybe we can use SPI for this plugin,FYR.

**Comment by lidaoyang** [comment]
> When the configuration encryption plug-in is designed, Alibaba Cloud's encryption is introduced as one of the encryption plug-ins. At present, I personally cannot agree to this implementation.

从NacosConfigService看到 ConfigFilterChainManager是private的，没有对外接口，只能在这个类中修改，而且getServerConfig中没有把acm接口返回的encryptedDataKey存放到数组中，如果要添加这个功能还是要侵入一些代码的。

**Pull request closed without merging**
