### PR TITLE
[ISSUE #963] to support registering instance with host name

### PR DESCRIPTION
**Pull request by Albert-Hugo**
## What is the purpose of the change

To support registering instance with host name

## Brief changelog

Only ip address contain ':' will be validated ip format.

**from** 
`public boolean validate() {

        Matcher matcher = IP_PATTERN.matcher(getIp() + ":" + getPort());
        if (!matcher.matches()) {
            return false;
        }

        if (getWeight() > MAX_WEIGHT_VALUE || getWeight() < MIN_WEIGHT_VALUE) {
            return false;
        }

        return true;
    }`
**to** 

```
public boolean validate() {

        if(getIp().contains(":")){
            Matcher matcher = IP_PATTERN.matcher(getIp() + ":" + getPort());
            if (!matcher.matches()) {
                return false;
            }
        }

        if (getWeight() > MAX_WEIGHT_VALUE || getWeight() < MIN_WEIGHT_VALUE) {
            return false;
        }

        return true;
    }
```

### CODE REVIEW

**Comment by Albert-Hugo** [comment]
fixed the build bug

**Comment by Albert-Hugo** [comment]
@nkorange Why the Contributor License Agreement is still pending ? I should have signed it.

**Comment by nkorange** [comment]
> @nkorange Why the Contributor License Agreement is still pending ? I should have signed it.

I think you used another github account to commit your code: https://github.com/IdoFree , not your current account: https://github.com/Albert-Hugo

**Comment by Albert-Hugo** [comment]
ok , then I will open another to fix it .

**Pull request closed without merging**
