### PR TITLE
[ISSUE #7999] Add configType field in ConfigHistory 

### LINKED ISSUE #7999: 2.0.4 Configuration rollback format exception
After the nacos 2.0.4 configuration is rolled back, the original yaml configuration format becomes TEXT

### PR DESCRIPTION
**Pull request by onewe**
Close #7999 

- Add configType field in the ConfigHistoryInfo
- add config_type field in the nacos-mysql.sql
- add config_type field in the schema.sql
- Config rollback page keep parameters when go back to history page
- Remove invalid parameters

改动:
- 在ConfigHistoryInfo实体中添加configType字段
- 在nacos-mysql.sql脚本中添加config_type字段
- 在schema.sql脚本中添加config_type字段
- 修复从回滚配置页面跳回列表页面参数丢失问题
- 修复历史列表请求400,移除逻辑矛盾的断言
## What is the purpose of the change

XXXXX

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [x] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Comment by KomachiSion** [comment]
I think it should more discuss in issue first.

**Comment by onewe** [comment]
Well

**Comment by realJackSun** [comment]
@onewe Some of the CI did not pass, Could you commit somthing to rerun the CI?
有一些CI没有通过，可能是由于一些随机项的干扰导致，可否commit一些东西，让CI重新跑一遍。

**Comment by onewe** [comment]
ok, I will resolve it on next Tuesday.

**Comment by onewe** [comment]
感觉这改动还是太大了点,涉及到数据库字段的变更.

**Comment by KomachiSion** [comment]
See issue

**Pull request closed without merging**
