### PR TITLE
[ISSUE-#4262] Fix public namespace permission problem

### PR DESCRIPTION
**Pull request by horizonzy**
## What is the purpose of the change
For-#4262, #3524

### CODE REVIEW

**Review by Maijh97 — APPROVED** [review]

**Review by sanxun0325 — APPROVED** [review]

**Comment by KomachiSion** [comment]
What will happen if users upgrade from old version? 
Whether old client can use after this PR merged?

**Comment by horizonzy** [comment]
> What will happen if users upgrade from old version?
> Whether old client can use after this PR merged?

this is server side logic, whatever user set namespace with value `public` or not set, server all handle it to `:*:*`, it match our permission design.

**Comment by KomachiSion** [comment]
So only affect the namespace during authorization verification, and still use the user's input for actual operations?

**Comment by horizonzy** [comment]
yeah, this handle just affect auth process, if some operation need handle namespace, just use namespaceUtils by itsself.

**Review by KomachiSion — APPROVED** [review]

**Pull request merged**
