### PR TITLE
[ISSUE #4452]Can nacos support the environment configuration comparison function similar to appolo?

### PR DESCRIPTION
**Pull request by BlackBAKA**
# What is the purpose of the change

issue- #4452

### CODE REVIEW

**Comment by KomachiSion** [comment]
I think your implementation is complicated. I suggest you refer to the comparing for release configuration with the historical version and use that way to implement this features.

**Comment by BlackBAKA** [comment]
> I think your implementation is complicated. I suggest you refer to the comparing for release configuration with the historical version and use that way to implement this features.

Do you means compare config to their history, not compare to any config?

**Comment by KomachiSion** [comment]
> > I think your implementation is complicated. I suggest you refer to the comparing for release configuration with the historical version and use that way to implement this features.
> 
> Do you means compare config to their history, not compare to any config?

No, I mean you can imitate the features of comparing history to realize the feature of comparing different environment configurations.

**Comment by KomachiSion** [comment]
Like this
image

**Comment by KomachiSion** [comment]
This feature has finished.

**Pull request closed without merging**
