### PR TITLE
[ISSUE #8345] Check cluster name in client when registerInstance

### PR DESCRIPTION
**Pull request by liqipeng**
## What is the purpose of the change

Do some optimization for #8371 .

## Brief changelog

Check cluster name in client when registerInstance

## Verifying this change

See unit test

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Review by KomachiSion — CHANGES_REQUESTED** [review]
Server part also need do check to avoid users use openAPI register illegal cluster

**Comment by KomachiSion** [comment]
> > Server part also need do check to avoid users use openAPI register illegal cluster
> 
> ok

Can you add check logic in server handler and api?

**Comment by liqipeng** [comment]
> > > Server part also need do check to avoid users use openAPI register illegal cluster
> > 
> > 
> > ok
> 
> Can you add check logic in server handler and api?

Yes, I will process it. A little busy, maybe days later.

**Comment by KomachiSion** [comment]
> > > > Server part also need do check to avoid users use openAPI register illegal cluster
> > > 
> > > 
> > > ok
> > 
> > 
> > Can you add check logic in server handler and api?
> 
> @KomachiSion Maybe client-side changes could be merged first if it is ok. And I will modify server-side ASAP. A little busy recently, maybe days later.

OK

**Review by KomachiSion — APPROVED** [review]

**Pull request merged**
