### PR TITLE
Update the sofa-jraft version to resolve the issue of the server cannot connect to the client

### PR DESCRIPTION
**Pull request by AlchemyDing**
resolve [issue](https://github.com/alibaba/nacos/issues/11422)

### CODE REVIEW

**Comment by KomachiSion** [comment]
The unit test can't pass, please fix them.

**Comment by AlchemyDing** [comment]
> The unit test can't pass, please fix them.

Fixed. Can you help me take a look.

**Comment by KomachiSion** [comment]
CI run start, waiting for result

**Comment by KomachiSion** [comment]
It seems CI can't pass still.

**Comment by AlchemyDing** [comment]
> It seems CI can't pass still.

Can you help me to solve this problem?

**Comment by AlchemyDing** [comment]
> ```
> Error:    JRaftServerTest.unnecessary Mockito stubbings » UnnecessaryStubbing 
> ```
> 
> It seems some mock no used in JRaftServerTest. Can you see the detail log and found which mock item is no used and remove it?

@CLAassistant 
```
Error:  Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.117 s <<< FAILURE! - in com.alibaba.nacos.core.distributed.raft.JRaftServerTest
Error:  unnecessary Mockito stubbings(com.alibaba.nacos.core.distributed.raft.JRaftServerTest)  Time elapsed: 0.029 s  <<< ERROR!
org.mockito.exceptions.misusing.UnnecessaryStubbingException: 

Unnecessary stubbings detected in test class: JRaftServerTest
Clean & maintainable test code requires zero unnecessary code.
Following stubbings are unnecessary (click to navigate to relevant line of code):
  1. -> at com.alibaba.nacos.core.distributed.raft.JRaftServerTest.mockcliClientService(JRaftServerTest.java:199)
Please remove unnecessary stubbings or use 'lenient' strictness. More info: javadoc for UnnecessaryStubbingException class.
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:52)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
```
I have removed `JRaftServerTest.java:199`

**Review by KomachiSion — APPROVED** [review]

**Pull request merged**
