### PR TITLE
Fix the issue of abnormal page loading on the first start in the front-end development environment.(related issue #12944)

### PR DESCRIPTION
**Pull request by littlesparklet**
## What is the purpose of the change

To fix the issue of abnormal page loading on the first start in the front-end development environment.

The key issue lies in the failure to correctly locate the hot module replacement (HMR) entry point during the first startup, which prevents the browser from initiating a WebSocket connection to establish communication with the Webpack Dev Server on the first launch.

### CODE REVIEW

**Comment by KomachiSion** [comment]
There is one file with conflict.

**Comment by KomachiSion** [comment]
And the conflict file changes seems not relative this problem. 

Is it from others change?

**Comment by littlesparklet** [comment]
I`ll repair it later


***@***.***
 
From: 杨翊 SionYang
Date: 2024-12-16 17:44
To: alibaba/nacos
CC: littlesparklet; Author
Subject: Re: [alibaba/nacos] Fix the issue of abnormal page loading on the first start in the front-end development environment.(related issue #12944) (PR #12948)
And the conflict file changes seems not relative this problem.
Is it from others change?

**Comment by wuyfee** [comment]
$\color{green}{SUCCESS}$
[DETAILS](https://github.com/alibaba/nacos/actions/runs/12349756100)
 ✅ - docker:   success 
 ✅ - deploy (standalone & cluster & standalone_auth):   success 
 ✅ - e2e-java-test (standalone & cluster & standalone_auth):   success 
 ✅ - e2e-go-test (standalone & cluster):   success 
 ✅ - e2e-cpp-test (standalone & cluster):   success 
 ✅ - e2e-csharp-test (standalone & cluster):   success 
 ✅ - e2e-nodejs-test (standalone & cluster):   success 
 ✅ - e2e-python-test (standalone & cluster):   success 
 ✅ - clean (standalone & cluster & standalone_auth):   success

**Pull request closed without merging**
