### PR TITLE
[ISSUE #11926] The abnormal exit mechanism does not take effect

### PR DESCRIPTION
**Pull request by syshenyao**
Bug fix https://github.com/alibaba/nacos/issues/11926 The abnormal exit mechanism does not take effect

### CODE REVIEW

**Review by KomachiSion — APPROVED** [review]

**Comment by syshenyao** [comment]
Continuous Integration/CI (Ubuntu latest, 8) results：
image

Can the local test pass, but Continuous Integration/CI (Ubuntu latest, 8) cannot?

**Comment by KomachiSion** [comment]
Please rebase from develop branch， the ut problem has been fixed

**Comment by syshenyao** [comment]
> Please rebase from develop branch， the ut problem has been fixed

Okay

**Comment by KomachiSion** [comment]
The Pr include others commit, please fix it.

If you can't, I suggest you checkout from develop branch and cherry-pick your commit into new branch and submit new PR.

**Pull request closed without merging**
