### PR TITLE
[ISSUE #8050] Fix config that can't read environment args 

### LINKED ISSUE #8050: 通过环境变量设置nacos.naming.client.expired.time不生效
环境信息：
nacos服务端版本：2.0.3，
客户端使用：spring-cloud-starter-alibaba-nacos-discovery的2.2.5.RELEASE

现象：

通过源码启动nacos，并通过环境变量注入nacos.naming.client.expired.time设置为较长
image

注册临时服务，等服务上线后，停掉临时服务。在服务端进行检查时候，如图会检测客户端的过期时间，通过获取ClientConfig的实例得到该参数
image
但在ClientConfig代码中，初始化该对象时候调用了父类AbstractDynamicConfig的resetConfig()方法并通过子类的getConfigFromEnv()方法从环境变量中获取到了nacos.naming.client.expired.time的值并赋给clientExpiredTime，但子类ClientConfig初始化过程中又重置了clientExpiredTime为默认的3分钟。导致无论如何都无法通过环境变量设置该值
企业微信截图_ba23aa4e-d2b9-4c0f-8db4-28cdc9e7be1a

### PR DESCRIPTION
**Pull request by onewe**
Close #8050

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

XXXXX

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [x] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Review by KomachiSion — CHANGES_REQUESTED** [review]
Bad fix. Only move the resetConfig method in DistroConfig can fix it.

**Comment by onewe** [comment]
Could you tell me the reason?
Pardon me that I'm a newbie.

**Comment by onewe** [comment]
Could you tell me how to deal with it

**Comment by onewe** [comment]
How about this way?

**Review by KomachiSion — CHANGES_REQUESTED** [review]
太麻烦了， 直接把reset方法下移到子类构造方法里就好了

**Comment by onewe** [comment]
Ok

**Review by KomachiSion — APPROVED** [review]

**Pull request merged**
