### PR TITLE
Optimization renamed variable

### PR DESCRIPTION
**Pull request by MisterChangRay**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

In the process of reading the source code, it is found that the word is misspelled in the 'envutil' tool class:
在阅读源码的过程中， 发现在 `EnvUtil` 工具类中， 发现一处单词拼写错误：

源代码：
```java
  // 变量名：amorayTagTmp  
 // 这里的 amoray, 从上下文分析。 此时应为 amory
 // 可能是大佬手速太快了 [手动狗头]
  List<String> amorayTagTmp = headers.get(Constants.AMORY_TAG);
            if (amorayTagTmp == null) {
                if (selfAmorayTag != null) {
                    selfAmorayTag = null;
                    LOGGER.warn("selfAmoryTag:null");
                }
```

In addition, there are several variables in this category, and the small hump is not used. 
另外还有此类中的几个 变量， 未使用小驼峰。 统一修改为小驼峰了。

如:
```java
List<String> vipserverTagTmp = headers.get(Constants.VIPSERVER_TAG);
```

## Verifying this change

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Review by Oliverwqcwrw — DISMISSED** [review]
LGTM

**Review by li-xiao-shuang — DISMISSED** [review]

**Review by KomachiSion — CHANGES_REQUESTED** [review]
Vipserver is a whole word, not two words

**Comment by MisterChangRay** [comment]
> Vipserver is a whole word, not two words, No need camel way.

thank y

recover renamed  Vipserver

**Comment by KomachiSion** [comment]
Sorry, Can you rebase `develop` branch for this PR? we need run coverage in CI.

**Pull request closed without merging**
