### PR TITLE
[ISSUE-#2768].fix parse resultset exception when dumpchange

### PR DESCRIPTION
**Pull request by horizonzy**
## What is the purpose of the change

fix parse resultset exception when dumpchange

### CODE REVIEW

**Comment by horizonzy** [comment]
@chuntaojun check it

**Comment by chuntaojun** [comment]
#2768

**Comment by chuntaojun** [comment]
I think it would be more accurate to add a query for type

**Comment by chuntaojun** [comment]
you can see here ：https://github.com/alibaba/nacos/pull/2680

**Comment by horizonzy** [comment]
i see.i will close it



发自我的iPhone


------------------ Original ------------------

**Pull request closed without merging**
