### PR TITLE
remove useless lastActiveTime

### PR DESCRIPTION
**Pull request by xingdong015**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

XXXXX

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Comment by shiyiyue1102** [comment]
ActiveTime is a basic info for a connection meta, it may be used to check connection is active in implementation of RuntimeConnectionEjector,so it should not be deleted

**Comment by xingdong015** [comment]
> ActiveTime is a basic info for a connection meta, it may be used to check connection is active in implementation of RuntimeConnectionEjector,so it should not be deleted

Why not let the channel of grpc manage the survival status of the connection by itself. Instead, use your own way of maintaining the last active time of the connection

**Comment by xingdong015** [comment]
> ActiveTime is a basic info for a connection meta, it may be used to check connection is active in implementation of RuntimeConnectionEjector,so it should not be deleted

Why do you need to manually maintain the last active time of the connection to Ejector connection. Instead of managing the survival status of the connection through grpc's own channel. grpc's ServerBuilder also has some control parameters to control the life cycle of the connection.

At the same time, I also see that the previous submission has deleted the code of removing the connection through the active time #9653

**Comment by shiyiyue1102** [comment]
> > ActiveTime is a basic info for a connection meta, it may be used to check connection is active in implementation of RuntimeConnectionEjector,so it should not be deleted
> 
> Why do you need to manually maintain the last active time of the connection to Ejector connection. Instead of managing the survival status of the connection through grpc's own channel. grpc's ServerBuilder also has some control parameters to control the life cycle of the connection.
> 
> At the same time, I also see that the previous submission has deleted the code of removing the connection through the active time #9653

grpc is just a implementation of connection in our design, we need our own active detection mechanism，in the issue #9653 I deleted the active time detection code , it seems to needed be restored

**Comment by xingdong015** [comment]
> > > ActiveTime is a basic info for a connection meta, it may be used to check connection is active in implementation of RuntimeConnectionEjector,so it should not be deleted
> > 
> > 
> > Why do you need to manually maintain the last active time of the connection to Ejector connection. Instead of managing the survival status of the connection through grpc's own channel. grpc's ServerBuilder also has some control parameters to control the life cycle of the connection.
> > At the same time, I also see that the previous submission has deleted the code of removing the connection through the active time #9653
> 
> grpc is just a implementation of connection in our design, we need our own active detection mechanism，in the issue #9653 I deleted the active time detection code , it seems to needed be restored

I understand what you mean. Can I understand it like this. GrpcConnection is just an implementation of abstract Connection, although grpc can automatically manage the connection state through some parameters [参考](https://github.com/grpc/proposal/blob/master/A9-server-side-conn-mgt.md) 
But other connection implementations may not automatically manage the connection state. So we need to manually monitor the active state of the connection. In order to close the connection at the right time and release the resources on the server side. Avoid wasting resources.

**Comment by shiyiyue1102** [comment]
> 

yes, you are right

**Comment by junziln** [comment]
> > > ActiveTime 是连接元的基本信息，在 RuntimeConnectionEjector 的实现中可以用来检查连接是否处于活动状态，因此不应删除
> > 
> > 
> > 为什么需要手动维护连接到 Ejector 连接的上次活动时间。而不是通过 grpc 自己的通道管理连接的生存状态。gRPC 的 ServerBuilder 也有一些控制参数来控制连接的生命周期。
> > 同时我还看到之前提交删除了通过活动时间删除连接的代码 #9653
> 
> gRPC 只是我们设计中 connection 的一个实现，我们需要自己的主动检测机制，在 [issue #9653](https://github.com/alibaba/nacos/pull/9653) 中我删除了主动时间检测代码，好像需要恢复一下

有个问题啊         不是说要恢复一下       为什么看了几个版本还是没有恢复呢       那现在到底是哪种呢？我看2.2.0只有都改了的

**Pull request closed without merging**
