### PR TITLE
Use MD5 value as file path to prevent errors caused by long file names.

### LINKED ISSUE #3605: (File name too long)
**Describe the bug**
多个nacos节点(3个), 配置中心地址叠加自定义namespace 之后字符过长, 导致程序启动时保存本地配置快照文件名称太长无法保存

Multiple nacos nodes (3), after the configuration center address is superimposed on the custom namespace, the characters are too long, causing the local configuration snapshot file name to be too long to save when the program starts

**Desktop (please complete the following information):**
 - OS: [Centos7.6, Docker CE 19.03.5, Kubernetes 1.18.0]
 - Version [nacos-server 1.3.2, nacos-client 1.3.2]
 - Module [config]
 - SDK [com.alibaba.nacos-nacos-client]

**Additional context**

```
2020-08-14 03:19:59.025 ERROR 1 --- [      elastic-7] c.a.n.c.c.impl.LocalConfigInfoProcessor  : [fixed-magical-nacos-server-0.magical-nacos-headless.default.svc.cluster.local_8848-magical-nacos-server-1.magical-nacos-headless.default.svc.cluster.local_8848-magical-nacos-server-2.magical-nacos-headless.default.svc.cluster.local_8848-d96ed582-904a-451d-9f56-34b31626a1cc] save snapshot error
2020-08-14 03:19:59.027 ERROR 1 --- [      elastic-7] c.a.n.c.c.impl.LocalConfigInfoProcessor  : [fixed-magical-nacos-server-0.magical-nacos-headless.default.svc.cluster.local_8848-magical-nacos-server-1.magical-nacos-headless.default.svc.cluster.local_8848-magical-nacos-server-2.magical-nacos-headless.default.svc.cluster.local_8848-d96ed582-904a-451d-9f56-34b31626a1cc] save snapshot error, /root/nacos/config/fixed-magical-nacos-server-0.magical-nacos-headless.default.svc.cluster.local_8848-magical-nacos-server-1.magical-nacos-headless.default.svc.cluster.local_8848-magical-nacos-server-2.magical-nacos-headless.default.svc.cluster.local_8848-d96ed582-904a-451d-9f56-34b31626a1cc_nacos/snapshot-tenant/d96ed582-904a-451d-9f56-34b31626a1cc/SENTINEL_FLOW_TEST_GROUP/magical-gateway-Sentinel
java.io.FileNotFoundException: /root/nacos/config/fixed-magical-nacos-server-0.magical-nacos-headless.default.svc.cluster.local_8848-magical-nacos-server-1.magical-nacos-headless.default.svc.cluster.local_8848-magical-nacos-server-2.magical-nacos-headless.default.svc.cluster.local_8848-d96ed582-904a-451d-9f56-34b31626a1cc_nacos/snapshot-tenant/d96ed582-904a-451d-9f56-34b31626a1cc/SENTINEL_FLOW_TEST_GROUP/magical-gateway-Sentinel (File name too long)
	at java.io.FileOutputStream.open0(Native Method) ~[na:1.8.0_202]
	at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[na:1.8.0_202]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[na:1.8.0_202]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162) ~[na:1.8.0_202]
	at com.alibaba.nacos.common.utils.IoUtils.writeStringToFile(IoUtils.java:121) ~[nacos-common-1.3.2.jar!/:na]
	at com.alibaba.nacos.client.config.impl.LocalConfigInfoProcessor.saveSnapshot(LocalConfigInfoProcessor.java:132) ~[nacos-client-1.3.2.jar!/:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:309) [nacos-client-1.3.2.jar!/:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:149) [nacos-client-1.3.2.jar!/:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:97) [nacos-client-1.3.2.jar!/:na]
	at com.alibaba.csp.sentinel.datasource.nacos.NacosDataSource.readSource(NacosDataSource.java:141) [sentinel-datasource-nacos-1.7.1.jar!/:na]
	at com.alibaba.csp.sentinel.datasource.nacos.NacosDataSource.readSource(NacosDataSource.java:42) [sentinel-datasource-nacos-1.7.1.jar!/:na]
	at com.alibaba.csp.sentinel.datasource.AbstractDataSource.loadConfig(AbstractDataSource.java:44) [sentinel-datasource-extension-1.7.1.jar!/:na]
	at com.alibaba.cloud.sentinel.endpoint.SentinelHealthIndicator.doHealthCheck(SentinelHealthIndicator.java:128) [spring-cloud-starter-alibaba-sentinel-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82) [spring-boot-actuator-2.1.16.RELEASE.jar!/:2.1.16.RELEASE]
	at org.springframework.boot.actuate.health.HealthIndicatorReactiveAdapter.invoke(HealthIndicatorReactiveAdapter.java:48) [spring-boot-actuator-2.1.16.RELEASE.jar!/:2.1.16.RELEASE]
	at org.springframework.boot.actuate.health.HealthIndicatorReactiveAdapter.lambda$null$0(HealthIndicatorReactiveAdapter.java:43) [spring-boot-actuator-2.1.16.RELEASE.jar!/:2.1.16.RELEASE]
	at reactor.core.scheduler.ElasticScheduler$DirectScheduleTask.run(ElasticScheduler.java:292) ~[reactor-core-3.2.19.RELEASE.jar!/:3.2.19.RELEASE]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:50) ~[reactor-core-3.2.19.RELEASE.jar!/:3.2.19.RELEASE]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:27) ~[reactor-core-3.2.19.RELEASE.jar!/:3.2.19.RELEASE]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_202]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_202]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_202]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_202]
```

### LINKED ISSUE #5387: 设置nacos客户端本地缓存文件名称
question:
      中文： nacos客户端的server-addr配置太长时，nacos生成缓存文件（fixed-xxx）受系统的限制（超过系统允许的长度）。请问是否有配置本地缓存文件名称的配置。
       english:   When the server-addr configuration of the nacos client is too long, the cache file (fixed-xxx) generated by nacos is restricted by the system (exceeding the length allowed by the system). Is there a configuration to configure the name of the local cache file?

### PR DESCRIPTION
**Pull request by myifeng**
## What is the purpose of the change

Use MD5 value as file path to prevent errors caused by long file names.

FIX #5387 

FIX #3605 

## Brief changelog

The path name of the snapshot file has a length limit, but sometimes the length of envName may exceed this limit, leading to errors.

Currently, nacos uses serverUrls for concatenation as file names, which determines that if the urls are long enough or have a large number, it will cause this problem.

```java
if (isFixed) {
                serverName = FIXED_NAME + "-" + (StringUtils.isNotBlank(namespace) ? (StringUtils.trim(namespace) + "-")
                        : "") + getFixedNameSuffix(serverUrls.toArray(new String[0]));
            } else {
                //if use endpoint ,  use endpoint ,content path ,serverlist name
                serverName = CUSTOM_NAME + "-" + String
                        .join("_", endpoint, String.valueOf(endpointPort), contentPath, serverListName) + (
                        StringUtils.isNotBlank(namespace) ? ("_" + StringUtils.trim(namespace)) : "");
            }
```

Sometimes the URL cannot be shortened because it is a valid URL (such as `magic-nacos-server-0.magic-nacos-headers. default.svc.cluster.local:8848`). Therefore, the relevant logic should be modified to ensure that there is no error with a file name that is too long

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Comment by shiyiyue1102** [comment]
you can pass a "serverName" param into properties when constructing NacosConfigService ,which will  determine local file snapshot  path instead of joining server ip list since nacos-client 2.1.0

**Comment by shiyiyue1102** [comment]
simplifying  the snapshot file path is also a reasonable way, and  I recommend to  keep some characters of server name,  that is
 static String simplyEnvNameIfOverLimit(String envName) {
        if (StringUtils.isNotBlank(envName) && envName.length() > MAX_ENV_NAME_LENGTH) {
            return envName.substring(0, MAX_ENV_NAME_LENGTH) + MD5Utils.md5Hex(envName,"UTF8");
        }
        return envName;
    }

**Comment by myifeng** [comment]
> simplifying the snapshot file path is also a reasonable way, and I recommend to keep some characters of server name.
> 
> for example :
> 
> static String simplyEnvNameIfOverLimit(String envName) { if (StringUtils.isNotBlank(envName) && envName.length() > MAX_ENV_NAME_LENGTH) { return envName.substring(0, MAX_ENV_NAME_LENGTH) + MD5Utils.md5Hex(envName,"UTF8"); } return envName; }.

That is indeed a solution, but if the serviceName is not configured, the issue still exists in nacos, which will result in nacos not working, which is very bad.

**Comment by myifeng** [comment]
**This directory name should be internal to NACOS. In theory, developers should not know its existence, let alone configure it.** 

**Isn't that the case？**

**Comment by shiyiyue1102** [comment]
> **This directory name should be internal to NACOS. In theory, developers should not know its existence, let alone configure it.**
> 
> **Isn't that the case？**

 Users should check the local snapshot file content when locating problems ,so you can't just set the local path to a simple md5 value.

**Comment by myifeng** [comment]
> > **This directory name should be internal to NACOS. In theory, developers should not know its existence, let alone configure it.**
> > **Isn't that the case？**
> 
> Users should check the local snapshot file content when locating problems ,so you can't just set the local path to a simple md5 value.

_**Wouldn't it be more convenient to display the content of the snapshot file on the NACOS webpage to locate the problem?**_

So we should fix this issue, even with MD5, users can still locate the file.

What we need to do is to try to avoid problems, rather than letting users locate and fix them themselves.

Don't put the cart before the horse.

**Comment by shiyiyue1102** [comment]
> just


> > > **This directory name should be internal to NACOS. In theory, developers should not know its existence, let alone configure it.**
> > > **Isn't that the case？**
> > 
> > 
> > Users should check the local snapshot file content when locating problems ,so you can't just set the local path to a simple md5 value.
> 
> _**Wouldn't it be more convenient to display the content of the snapshot file on the NACOS webpage to locate the problem?**_
> 
> So we should fix this issue, even with MD5, users can still locate the file.
> 
> What we need to do is to try to avoid problems, rather than letting users locate and fix them themselves.
> 
> Don't put the cart before the horse.

As I said above , I approved that this  problem should be fixed , and in the mean time , we should also consider  the convenience of locating problems for users, so we should't just set local snapshot direct to a unrecognizable md5 value.

You can take a look at the meaning of this code again 

static String simplyEnvNameIfOverLimit(String envName) {
if (StringUtils.isNotBlank(envName) && envName.length() > MAX_ENV_NAME_LENGTH) {
return envName.substring(0, MAX_ENV_NAME_LENGTH) + MD5Utils.md5Hex(envName,"UTF8");
}
return envName;
}

**Comment by KomachiSion** [comment]
No more response from author, It seems some problem reviewer submitted not solved

**Pull request closed without merging**
