### PR TITLE
[Optimize] Set interrupted flag to caller

### PR DESCRIPTION
**Pull request by Oliverwqcwrw**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

Set interrupted flag to caller

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [x] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Review by KomachiSion — COMMENTED** [review]
I can't get why change in this PR.

**Comment by Oliverwqcwrw** [comment]
If we catch InterruptedException but do nothing,This can cause the thread closing delay and lost the interrupted thread info,So we should return interrupted flag to caller and deal the interrupted thread

**Comment by KomachiSion** [comment]
I don't think so, InterruptedException only stop the sleep and wait lock operation, the thread need to do other logic. Not means the thread need be interrupted

**Comment by KomachiSion** [comment]
> InterruptedException not only stop the sleep and wait lock operation,It can be interrupted by any thread if need,It should be return the interrupted flag to the caller,Otherwise,The thread can not know what do next

Whether cause the following logic will not execute or cause other problem? I think the flag be set will cause the thread has some different habavior.

**Comment by Oliverwqcwrw** [comment]
If the interrupt status is not set, the thread will be delayed close and may occupy thread resources

**Comment by KomachiSion** [comment]
delayed close can be accepted, but if set flag cause thread early recycling can't be accepted.

**Comment by Oliverwqcwrw** [comment]
Delay close is also an optimistic idea and may not be closed and occupy thread resources.

So I think return the interrupted flag to caller better

**Review by KomachiSion — APPROVED** [review]
ok

**Pull request merged**
