### PR TITLE
#2855

### PR DESCRIPTION
**Pull request by yfh0918**
needs to close GZIPInputStream manually

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

GZIPInputStream流使用完未关闭。压测场景下存在内存泄露风险

## Brief changelog

InputStream from HttpURLConnection can be closed automatically,but new GZIPInputStream can't be closed automatically
so needs to close it manually 

## Verifying this change

InputStream from HttpURLConnection can be closed automatically,but new GZIPInputStream can't be closed automatically
so needs to close it manually 

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Comment by chuntaojun** [comment]
please sign cla

**Comment by yfh0918** [comment]
I have signed the CLA for alibaba/nacos

**Comment by chuntaojun** [comment]
Is user.name github when you commit the code? I see your submission record, it doesn't look like it

**Comment by yfh0918** [comment]
> Is user.name github when you commit the code? I see your submission record, it doesn't look like it

i have changed github name and merge request again

**Pull request merged**
