### PR TITLE
Support for ibm J9

### PR DESCRIPTION
**Pull request by lyh200**
Now system metrics are obtained from com.sun.management.OperatingSystemMXBean for HotSpot JVM, but these are in com.ibm.lang.management.OperatingSystemMXBean for Ibm J9, so need to deduce the target source.

### CODE REVIEW

**Comment by KomachiSion** [comment]
CI can't pass, please fix it first

**Comment by lyh200** [comment]
> CI can't pass, please fix it first

done!

**Comment by KomachiSion** [comment]
Sorry, Can you rebase `develop` branch for this PR? we need run coverage in CI.

**Comment by lyh200** [comment]
> Sorry, Can you rebase `develop` branch for this PR? we need run coverage in CI.

rebased!

**Comment by KomachiSion** [comment]
CI can't pass again, please us nacos codeStyle to reformat codes.

**Comment by lyh200** [comment]
Already formatted, please run ci again.

**Review by KomachiSion — APPROVED** [review]

**Pull request merged**
