### PR TITLE
[ISSUS #202]IN nacos-api module, do some code format&cleanup, correct some words spelling error

### PR DESCRIPTION
**Pull request by FrankBian**
## What is the purpose of the change

do some code format&cleanup and correct some spelling error in nacos-api module while reading code

## Brief changelog
1. Do code format in nacos-api module by Alibaba-Coding-Guideline-Analyze plugin
2. Do code cleanup in nacos-api module: remove unnecessary ```public``` method qualifier in ```interface``` definition
3. Correct some word spelling error, eg: listner

### CODE REVIEW

**Comment by FrankBian** [comment]
@xuechaos

**Comment by FrankBian** [comment]
@yanlinly herecan't request a

**Comment by FrankBian** [comment]
@yanlinly  Here.
I can't request a reviewer because I'm not a collaborator

**Comment by pguo65535** [comment]
@FrankBian thanks for your pull request on Nacos, I assigned the reviewer @yanlinly  for your pull request.

**Pull request closed without merging**
