### PR TITLE
[ISSUE #9760] Add postgres as an alternative external data source

### LINKED ISSUE #9760: Add postgresql as external data source support
In our circumanstance, we've only used PostgreSQL as our relational database storage. So we need a postgres external data source support.

A possible solution is implementing new postgres mapper implementation to support it.

### PR DESCRIPTION
**Pull request by cloorc**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

Add postgres as an alternative external data source support besides mysql.

## Brief changelog

1. Append new data source constant after `DataSourceConstant#MYSQL`;
2. Add new postgres mapper implementation;
3. Add UNIT-tests about this external data source implementation;
4. Add an integration of docker image in module `nacos-distribution`(optional, but mostly enough for deployment);

## Verifying this change

Fix #9760 #9499

### CODE REVIEW

**Comment by wuchubuzai2018** [comment]
你这个应该会被关闭掉，官方不允许提交数据库插件到主仓库

**Comment by cloorc** [comment]
> 你这个应该会被关闭掉，官方不允许提交数据库插件到主仓库

Sorry, I don't know this policy. Why should be like this?

**Comment by KomachiSion** [comment]
Please submit plugin to https://github.com/nacos-group/nacos-plugin

**Comment by KomachiSion** [comment]
There are some one has submit Postgresql plugin https://github.com/nacos-group/nacos-plugin/pull/18

**Comment by dylan-tao** [comment]
目前我这边已经开源支持postgresql的nacos-2.2.0版本（已投产），可以直接食用：https://github.com/dylan-tao/nacos-gaussdb

**Pull request closed without merging**
