### PR TITLE
[ISSUE #9819] fix bug-- can't update password.

### LINKED ISSUE #9819: nacos 2.2.0 版本，配置 nginx 反向代理时，无法通过 nginx 反向代理修改 nacos 密码
Nginx 配置如下：

upstream nacos-server {
  server 172.31.1.186:8848 weight=1 max_fails=2 fail_timeout=30s;
  server 172.31.1.186:8850 weight=1 max_fails=2 fail_timeout=30s;
  server 172.31.1.186:8852 weight=1 max_fails=2 fail_timeout=30s;
}

server {
    listen       8000;
    server_name  localhost;
    charset utf-8;
    default_type text/html;

    location ~ /nacos/* {
        proxy_pass http://nacos-server;
        client_body_buffer_size 10M;
        client_max_body_size 10G;
        proxy_buffers 1024 4k;
        proxy_read_timeout 300;
        proxy_next_upstream error timeout http_404;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Cookie $http_cookie;
        proxy_pass_header User-Agent;
        proxy_set_header Host $host:$server_port;
        proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;
    }
   
}

### PR DESCRIPTION
**Pull request by YunWZ**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

remove user info from request session

## Brief changelog

keep user info in `IdentityContextHolder`(threadlocal variable).

## Verifying this change

ref issuse #9819

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Review by KomachiSion — CHANGES_REQUESTED** [review]
这个修复没有看懂，为什么这样修复是可以修复问题的，并且是否会导致漏洞？

**Comment by YunWZ** [comment]
> 

当前版本的鉴权逻辑不通过spring-security完成,只有login接口会设置session--这回导致通过jwtToken调用修改密码接口时由于找不到session导致返回“session expired!“.

修复的逻辑就是, 在AuthFilter中,完成鉴权后,将identifyContext保存的session中,这样其他地方才可以正确获取用户信息.

**Comment by KomachiSion** [comment]
> > 
> 
> 当前版本的鉴权逻辑不通过spring-security完成,只有login接口会设置session--这回导致通过jwtToken调用修改密码接口时由于找不到session导致返回“session expired!“.
> 
> 修复的逻辑就是, 在AuthFilter中,完成鉴权后,将identifyContext保存的session中,这样其他地方才可以正确获取用户信息.

会不会在添加这个机制后有可以利用的漏洞绕过鉴权？

**Comment by YunWZ** [comment]
> > > 
> > 
> > 
> > 当前版本的鉴权逻辑不通过spring-security完成,只有login接口会设置session--这回导致通过jwtToken调用修改密码接口时由于找不到session导致返回“session expired!“.
> > 修复的逻辑就是, 在AuthFilter中,完成鉴权后,将identifyContext保存的session中,这样其他地方才可以正确获取用户信息.
> 
> 会不会在添加这个机制后有可以利用的漏洞绕过鉴权？

没有添加新的机制,原来的逻辑就是将用户信息保存在session中. 现在也是在完成鉴权认证后才将用户信息保存到session中.

**Review by KomachiSion — APPROVED** [review]

**Pull request merged**
