### PR TITLE
Feature #8941 Support Fuzzy Query in Authority Control--for api change.

### PR DESCRIPTION
**Pull request by zhouchunhai**
## What is the purpose of the change

Support Fuzzy Query in Authority Control.

## Brief changelog

Add api to support fuzzy and accurate search in user, role, permission page.

### CODE REVIEW

**Review by Rocbrad9 — APPROVED** [review]
That was easy

**Review by Rocbrad9 — CHANGES_REQUESTED** [review]
Is that compatible

**Review by KomachiSion — COMMENTED** [review]
if some one use old api without `search=accurate`, whether throw exception?

**Review by KomachiSion — CHANGES_REQUESTED** [review]
IT can't pass. need fix them.

**Comment by zhouchunhai** [comment]
CI report say UdpConnectTest throws an error, but i run it locally, it just pass without any error.

**Comment by KomachiSion** [comment]
> CI report say UdpConnectTest throws an error, but i run it locally, it just pass without any error.

I will rerun it several time

**Review by KomachiSion — APPROVED** [review]

**Pull request merged**
