### PR TITLE
English grammar update

### PR DESCRIPTION
**Pull request by GeorgeMuscat**
Corrected the english grammar on the README.md. This change also matches the description of the repository on Github.

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

Minor fix to the grammar in the opening line of the README to match the Github Repository.
This change will ensure the project maintains its professional image.

## Brief changelog

One commit, containing a minor change to the README grammar.

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

### CODE REVIEW

**Comment by wilsonwu** [comment]
Good update, please sign CLA first, thanks for your contribute.

**Comment by GeorgeMuscat** [comment]
> Good update, please sign CLA first, thanks for your contribute.

This has been done :)

**Review by Jan6896 — APPROVED** [review]

**Comment by wilsonwu** [comment]
Could any reviewer help to merge?

**Comment by GeorgeMuscat** [comment]
> Sorry, The CI has been fixed. Please rebase from develop branch.

I think I have done this now

**Comment by KomachiSion** [comment]
> > Sorry, The CI has been fixed. Please rebase from develop branch.
> 
> I think I have done this now

But the ci can't pass still

**Comment by KomachiSion** [comment]
CI can't pass and author not fix it for a long time.

**Pull request closed without merging**
