### PR TITLE
Change the invalid compare in NotifySingleService

### LINKED ISSUE #5585: The compare in NotifySingleService always return true.
**Describe the bug**
Please see the screenshot.
image

**Expected behavior**
the ClusterIps should use String type collection.

**Acutally behavior**
it's a Member type collection

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**
no

### PR DESCRIPTION
**Pull request by brotherlu-xcq**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

Fixes #5585 

## Brief changelog

change the compare

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Review by KomachiSion — CHANGES_REQUESTED** [review]
Your PR does not change anything and logic, the judgement also is always true. Your just get this warning disappear.

I think there are some reason for this code. For example, the target is removed from member, nacos server should remove the notify task.

**Comment by KomachiSion** [comment]
@shiyiyue1102  Can you help to review this PR.

**Comment by shiyiyue1102** [comment]
I check the code and found that this executors is not used anywhere, fix this 'bug' seems add useless threads

**Review by shiyiyue1102 — COMMENTED** [review]
setupNotifyExecutors seems not used by anywhere in the project ,could delete directly, fix this bug seems increases useless thread

**Review by shiyiyue1102 — APPROVED** [review]

**Review by KomachiSion — APPROVED** [review]

**Pull request merged**
