### PR TITLE
[ISSUE #11951] Fix the problem that the servicename and groupname are not resolved correctly when deleting an empty service instance

### PR DESCRIPTION
**Pull request by Happy-26**
Bug  fix [#11951 ](https://github.com/alibaba/nacos/issues/11951) 修改删除空服务实例时，服务名和分组名没有正确解析的问题

### CODE REVIEW

**Review by KomachiSion — CHANGES_REQUESTED** [review]
Can you help community to add unit test for this case?

**Comment by Happy-26** [comment]
It seems that a unit test already exists here[ServiceControllerTest](https://github.com/alibaba/nacos/blob/develop/naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java)

**Comment by KomachiSion** [comment]
> It seems that a unit test already exists here：[ServiceControllerTest](https://github.com/alibaba/nacos/blob/develop/naming/src/test/java/com/alibaba/nacos/naming/controllers/ServiceControllerTest.java)

Yes I know it, I mean the old one only check the UpdateServiceTraceEvent , not check DeregisterServiceTraceEvent

**Comment by KomachiSion** [comment]
> > It seems that a unit test already exists here：[ServiceControllerTest](https://github.com/alibaba/nacos/blob/develop/naming/src/test/java/com/alibaba/nacos/naming/controllers/ServiceControllerTest.java)
> 
> Yes I know it, I mean the old one only check the UpdateServiceTraceEvent , not check DeregisterServiceTraceEvent

Prefer you add the check for DeregisterServiceTraceEvent.

**Comment by Happy-26** [comment]
> > > It seems that a unit test already exists here：[ServiceControllerTest](https://github.com/alibaba/nacos/blob/develop/naming/src/test/java/com/alibaba/nacos/naming/controllers/ServiceControllerTest.java)
> > 
> > 
> > Yes I know it, I mean the old one only check the UpdateServiceTraceEvent , not check DeregisterServiceTraceEvent
> 
> Prefer you add the check for DeregisterServiceTraceEvent in UT.

I'm sorry I didn't understand how to write unit tests for Nacos. Do you mean to change it to this?

    @Before
    public void before() {
        super.before();
        subscriber = new SmartSubscriber() {
            @Override
            public List<Class<? extends Event>> subscribeTypes() {
                List<Class<? extends Event>> result = new LinkedList<>();
                result.add(UpdateServiceTraceEvent.class);
                result.add(DeregisterServiceTraceEvent.class);
                return result;
            }
            
            @Override
            public void onEvent(Event event) {
                eventReceivedClass = event.getClass();
            }
        };
        NotifyCenter.registerSubscriber(subscriber);
    }
    
    @After
    public void tearDown() throws Exception {
        NotifyCenter.deregisterSubscriber(subscriber);
        NotifyCenter.deregisterPublisher(UpdateServiceTraceEvent.class);
        NotifyCenter.deregisterPublisher(DeregisterServiceTraceEvent.class);
        eventReceivedClass = null;
    }

**Review by KomachiSion — APPROVED** [review]

**Pull request merged**
