### PR TITLE
The error message is not user-friendly when adding duplicate permissi…

### PR DESCRIPTION
**Pull request by littlesparklet**
…ons. (#12773)

## What is the purpose of the change

To solve this problem: The error message is not user-friendly when adding duplicate permissions

### CODE REVIEW

**Comment by KomachiSion** [comment]
whether depend on #12805?

**Comment by littlesparklet** [comment]
> depend

Yes, It indeed depends on https://github.com/alibaba/nacos/pull/12805. we work together on this.

**Comment by KomachiSion** [comment]
I comment in https://github.com/alibaba/nacos/pull/12805, the api response might be changed. console-ui may be need changes.

**Comment by wuyfee** [comment]
$\color{green}{SUCCESS}$
[DETAILS](https://github.com/alibaba/nacos/actions/runs/12081903655)
 ✅ - docker:   success 
 ✅ - deploy (standalone & cluster & standalone_auth):   success 
 ✅ - e2e-java-test (standalone & cluster & standalone_auth):   success 
 ✅ - e2e-go-test (standalone & cluster):   success 
 ✅ - e2e-cpp-test (standalone & cluster):   success 
 ✅ - e2e-csharp-test (standalone & cluster):   success 
 ✅ - e2e-nodejs-test (standalone & cluster):   success 
 ✅ - e2e-python-test (standalone & cluster):   success 
 ✅ - clean (standalone & cluster & standalone_auth):   success

**Comment by wuyfee** [comment]
$\color{green}{SUCCESS}$
[DETAILS](https://github.com/alibaba/nacos/actions/runs/12082082666)
 ✅ - docker:   success 
 ✅ - deploy (standalone & cluster & standalone_auth):   success 
 ✅ - e2e-java-test (standalone & cluster & standalone_auth):   success 
 ✅ - e2e-go-test (standalone & cluster):   success 
 ✅ - e2e-cpp-test (standalone & cluster):   success 
 ✅ - e2e-csharp-test (standalone & cluster):   success 
 ✅ - e2e-nodejs-test (standalone & cluster):   success 
 ✅ - e2e-python-test (standalone & cluster):   success 
 ✅ - clean (standalone & cluster & standalone_auth):   success

**Comment by littlesparklet** [comment]
> I comment in #12805, the api response might be changed. console-ui may be need changes.

The api response has changed, and I changed the console-ui according to the api response.

**Review by KomachiSion — APPROVED** [review]

**Pull request merged**
