### PR TITLE
Refactor the cache to replace guava

### PR DESCRIPTION
**Pull request by zzq1314zll**
Refactor the cache to replace guava. for #6503

### CODE REVIEW

**Comment by zzq1314zll** [comment]
第一次:
单线程put 测试:
>>> initCap:200 maxCap:200 dataCount: 1000
guavaCachePut: 90
myCachePut: 6
>>> initCap:500 maxCap:500 dataCount: 1000
guavaCachePut: 15
myCachePut: 2
>>> initCap:800 maxCap:800 dataCount: 1000
guavaCachePut: 5
myCachePut: 2
>>> initCap:1000 maxCap:1000 dataCount: 1000
guavaCachePut: 3
myCachePut: 0
======================================
>>> initCap:1000 maxCap:1000 dataCount: 5000
guavaCachePut: 12
myCachePut: 3
>>> initCap:2500 maxCap:2500 dataCount: 5000
guavaCachePut: 6
myCachePut: 2
>>> initCap:5000 maxCap:5000 dataCount: 5000
guavaCachePut: 2
myCachePut: 1
======================================
>>> initCap:2000 maxCap:2000 dataCount: 10000
guavaCachePut: 9
myCachePut: 3
>>> initCap:5000 maxCap:5000 dataCount: 10000
guavaCachePut: 6
myCachePut: 2
>>> initCap:8000 maxCap:8000 dataCount: 10000
guavaCachePut: 7
myCachePut: 3
>>> initCap:1000 maxCap:10000 dataCount: 10000
guavaCachePut: 4
myCachePut: 1

单线程get 测试:
>>> dataCount: 100000 get: 50000
guavaCacheGet: 52
>>> dataCount: 100000 get: 50000
guavaCacheGet: 17


多线程put 测试:
>>> initCap:10000 maxCap:10000 dataCount: 40000 threadCount: 4
guavaCachePutM: 4
myCachePutM: 3
>>> initCap:40000 maxCap:40000 dataCount: 40000 threadCount: 4
guavaCachePutM: 2
myCachePutM: 4
>>> initCap:40000 maxCap:40000 dataCount: 80000 threadCount: 8
guavaCachePutM: 25
myCachePutM: 6
>>> initCap:80000 maxCap:80000 dataCount: 80000 threadCount: 8
guavaCachePutM: 13
myCachePutM: 1

多线程get测试 测试:
>>> getCount: 40000 threadCount: 4
guavaCacheGetM: 3
myCacheGetM: 25
>>> getCount: 80000 threadCount: 8
guavaCacheGetM: 42
myCacheGetM: 18
>>> getCount: 160000 threadCount: 16
guavaCacheGetM: 39
myCacheGetM: 15

**Comment by zzq1314zll** [comment]
第二次：
单线程put 测试:
>>> initCap:200 maxCap:200 dataCount: 1000
guavaCachePut: 83
myCachePut: 4
>>> initCap:500 maxCap:500 dataCount: 1000
guavaCachePut: 5
myCachePut: 2
>>> initCap:800 maxCap:800 dataCount: 1000
guavaCachePut: 3
myCachePut: 0
>>> initCap:1000 maxCap:1000 dataCount: 1000
guavaCachePut: 1
myCachePut: 1
======================================
>>> initCap:1000 maxCap:1000 dataCount: 5000
guavaCachePut: 8
myCachePut: 2
>>> initCap:2500 maxCap:2500 dataCount: 5000
guavaCachePut: 5
myCachePut: 1
>>> initCap:5000 maxCap:5000 dataCount: 5000
guavaCachePut: 2
myCachePut: 1
======================================
>>> initCap:2000 maxCap:2000 dataCount: 10000
guavaCachePut: 8
myCachePut: 1
>>> initCap:5000 maxCap:5000 dataCount: 10000
guavaCachePut: 7
myCachePut: 1
>>> initCap:8000 maxCap:8000 dataCount: 10000
guavaCachePut: 7
myCachePut: 2
>>> initCap:1000 maxCap:10000 dataCount: 10000
guavaCachePut: 3
myCachePut: 2

单线程get 测试:
>>> dataCount: 100000 get: 50000
guavaCacheGet: 82
>>> dataCount: 100000 get: 50000
guavaCacheGet: 20


多线程put 测试:
>>> initCap:10000 maxCap:10000 dataCount: 40000 threadCount: 4
guavaCachePutM: 3
myCachePutM: 13
>>> initCap:40000 maxCap:40000 dataCount: 40000 threadCount: 4
guavaCachePutM: 6
myCachePutM: 2
>>> initCap:40000 maxCap:40000 dataCount: 80000 threadCount: 8
guavaCachePutM: 27
myCachePutM: 27
>>> initCap:80000 maxCap:80000 dataCount: 80000 threadCount: 8
guavaCachePutM: 3
myCachePutM: 2

多线程get测试 测试:
>>> getCount: 40000 threadCount: 4
guavaCacheGetM: 5
myCacheGetM: 39
>>> getCount: 80000 threadCount: 8
guavaCacheGetM: 26
myCacheGetM: 14
>>> getCount: 160000 threadCount: 16
guavaCacheGetM: 41
myCacheGetM: 10

**Comment by zzq1314zll** [comment]
第三次：
单线程put 测试:
>>> initCap:200 maxCap:200 dataCount: 1000
guavaCachePut: 86
myCachePut: 3
>>> initCap:500 maxCap:500 dataCount: 1000
guavaCachePut: 6
myCachePut: 1
>>> initCap:800 maxCap:800 dataCount: 1000
guavaCachePut: 2
myCachePut: 1
>>> initCap:1000 maxCap:1000 dataCount: 1000
guavaCachePut: 2
myCachePut: 1
======================================
>>> initCap:1000 maxCap:1000 dataCount: 5000
guavaCachePut: 8
myCachePut: 2
>>> initCap:2500 maxCap:2500 dataCount: 5000
guavaCachePut: 5
myCachePut: 1
>>> initCap:5000 maxCap:5000 dataCount: 5000
guavaCachePut: 2
myCachePut: 1
======================================
>>> initCap:2000 maxCap:2000 dataCount: 10000
guavaCachePut: 7
myCachePut: 2
>>> initCap:5000 maxCap:5000 dataCount: 10000
guavaCachePut: 9
myCachePut: 2
>>> initCap:8000 maxCap:8000 dataCount: 10000
guavaCachePut: 7
myCachePut: 2
>>> initCap:1000 maxCap:10000 dataCount: 10000
guavaCachePut: 3
myCachePut: 1

单线程get 测试:
>>> dataCount: 100000 get: 50000
guavaCacheGet: 64
>>> dataCount: 100000 get: 50000
guavaCacheGet: 42


多线程put 测试:
>>> initCap:10000 maxCap:10000 dataCount: 40000 threadCount: 4
guavaCachePutM: 3
myCachePutM: 4
>>> initCap:40000 maxCap:40000 dataCount: 40000 threadCount: 4
guavaCachePutM: 15
myCachePutM: 5
>>> initCap:40000 maxCap:40000 dataCount: 80000 threadCount: 8
guavaCachePutM: 10
myCachePutM: 7
>>> initCap:80000 maxCap:80000 dataCount: 80000 threadCount: 8
guavaCachePutM: 2
myCachePutM: 10

多线程get测试 测试:
>>> getCount: 40000 threadCount: 4
guavaCacheGetM: 3
myCacheGetM: 16
>>> getCount: 80000 threadCount: 8
guavaCacheGetM: 17
myCacheGetM: 4
>>> getCount: 160000 threadCount: 16
guavaCacheGetM: 18
myCacheGetM: 7

**Comment by zzq1314zll** [comment]
单线程： myCache性能 > guava Cache
多线程少的时候: guava cache 的性能 > myCache
线程多的时候: guava cache 性能 < myCache

**Review by KomachiSion — APPROVED** [review]

**Pull request merged**
