### PR TITLE
resolve issue #9318 add ldap filter config:caseSensitive

### PR DESCRIPTION
**Pull request by David-wu91**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

解决nacos提供的默认ldap鉴权实现更好的适配ldap服务（如微软AD域控）用户名不区分大小写的情况。

## Brief changelog

XX

## Verifying this change

默认情况下是改实现是大小写敏感的，也可以通过设置nacos.core.auth.ldap.case.sensitive=false调整默认ldap鉴权插件的用户名为大小写不敏感。

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Review by KomachiSion — APPROVED** [review]

**Comment by KomachiSion** [comment]
Please add some Unit test for your changes.

**Comment by KomachiSion** [comment]
CI can't pass.

**Comment by KomachiSion** [comment]
It seems checkstyle can't pass, please use nacos code style to reformat codes.

**Comment by David-wu91** [comment]
> Please add some Unit test for your changes.

通过jacoco查看LdapAuthenticationProviderTest单元测试类之前的实现，单元测试只覆盖到私有方法方法，社区是否对公有方法有单独的集成测试方案啊。由于本次变更未添加新的私有方法，请问是否仍需要添加单元测试代码呢？

**Comment by KomachiSion** [comment]
任何的改动有需要带UT，和私有还是公开方法无关。你需要新增的ut是开启开关后他会忽略大小写，关闭开关后和以前一致

**Comment by David-wu91** [comment]
> 任何的改动有需要带UT，和私有还是公开方法无关。你需要新增的ut是开启开关后他会忽略大小写，关闭开关后和以前一致

好的，因为看到之前的单元测试类没有测试公有方法所以咨询一下。
已对代码改动部分添加单元测试。

**Review by KomachiSion — APPROVED** [review]

**Pull request merged**
